// Only Thai and English are shipped as fully usable UI languages. The other
// locale maps below are kept for reference but are not offered in the picker.
export const languages=[
 ["th","ไทย"],["en","English"]
];
const t={
 th:{home:"Home",vocab:"คำศัพท์",practice:"ฝึกทักษะ",manage:"จัดการ",system:"ระบบ",flash:"Flashcard",match:"Match",cross:"Crossword",reading:"Reading",listening:"Listening",writing:"Writing",mock:"Mock Exam",weak:"จุดอ่อน",community:"Community",add:"เพิ่มเนื้อหา",mine:"เนื้อหาของฉัน",library:"คลังของฉัน",leaderboard:"อันดับ",account:"บัญชี",profile:"โปรไฟล์",settings:"ตั้งค่า"},
 en:{home:"Home",vocab:"Vocabulary",practice:"Practice Skills",manage:"Manage",system:"System",flash:"Flashcards",match:"Match",cross:"Crossword",reading:"Reading",listening:"Listening",writing:"Writing",mock:"Mock Exam",weak:"Weak Points",community:"Community",add:"Add Content",mine:"My Content",library:"My Library",leaderboard:"Leaderboard",account:"Account",profile:"Profile",pricing:"Pricing",settings:"Settings"},
 zh:{home:"主页",vocab:"词汇",practice:"技能练习",manage:"管理",system:"系统",flash:"单词卡",match:"配对",cross:"填字游戏",reading:"阅读",listening:"听力",writing:"写作",mock:"模拟考试",weak:"薄弱点",community:"社区",add:"添加内容",mine:"我的内容",library:"我的内容库",account:"账户",profile:"个人资料",pricing:"价格",settings:"设置"},
 ja:{home:"ホーム",vocab:"単語",practice:"スキル練習",manage:"管理",system:"システム",flash:"単語カード",match:"マッチ",cross:"クロスワード",reading:"リーディング",listening:"リスニング",writing:"ライティング",mock:"模擬試験",weak:"弱点",community:"コミュニティ",add:"コンテンツ追加",mine:"マイコンテンツ",library:"マイライブラリ",account:"アカウント",profile:"プロフィール",pricing:"料金",settings:"設定"},
 ko:{home:"홈",vocab:"어휘",practice:"기능 연습",manage:"관리",system:"시스템",flash:"플래시카드",match:"매치",cross:"크로스워드",reading:"읽기",listening:"듣기",writing:"쓰기",mock:"모의고사",weak:"취약점",community:"커뮤니티",add:"콘텐츠 추가",mine:"내 콘텐츠",library:"내 라이브러리",account:"계정",profile:"프로필",pricing:"요금",settings:"설정"},
 pt:{home:"Início",vocab:"Vocabulário",practice:"Prática",manage:"Gerenciar",system:"Sistema",flash:"Flashcards",match:"Combinar",cross:"Palavras cruzadas",reading:"Leitura",listening:"Compreensão oral",writing:"Escrita",mock:"Simulado",weak:"Pontos fracos",community:"Comunidade",add:"Adicionar conteúdo",mine:"Meu conteúdo",library:"Minha biblioteca",account:"Conta",profile:"Perfil",pricing:"Preços",settings:"Configurações"},
 de:{home:"Start",vocab:"Wortschatz",practice:"Fertigkeiten",manage:"Verwalten",system:"System",flash:"Karteikarten",match:"Zuordnen",cross:"Kreuzworträtsel",reading:"Lesen",listening:"Hören",writing:"Schreiben",mock:"Probetest",weak:"Schwachstellen",community:"Community",add:"Inhalt hinzufügen",mine:"Meine Inhalte",library:"Meine Bibliothek",account:"Konto",profile:"Profil",pricing:"Preise",settings:"Einstellungen"},
 ru:{home:"Главная",vocab:"Словарь",practice:"Навыки",manage:"Управление",system:"Система",flash:"Карточки",match:"Соответствия",cross:"Кроссворд",reading:"Чтение",listening:"Аудирование",writing:"Письмо",mock:"Пробный экзамен",weak:"Слабые места",community:"Сообщество",add:"Добавить материал",mine:"Мои материалы",library:"Моя библиотека",account:"Аккаунт",profile:"Профиль",pricing:"Тарифы",settings:"Настройки"},
 hi:{home:"होम",vocab:"शब्दावली",practice:"कौशल अभ्यास",manage:"प्रबंधन",system:"सिस्टम",flash:"फ़्लैशकार्ड",match:"मिलान",cross:"क्रॉसवर्ड",reading:"पठन",listening:"श्रवण",writing:"लेखन",mock:"मॉक परीक्षा",weak:"कमज़ोर क्षेत्र",community:"समुदाय",add:"सामग्री जोड़ें",mine:"मेरी सामग्री",library:"मेरी लाइब्रेरी",account:"खाता",profile:"प्रोफ़ाइल",pricing:"मूल्य",settings:"सेटिंग्स"}
};
export function tr(lang,key){return t[lang]?.[key]||t.en[key]||key}

const EN={
 "ฝึกภาษาอังกฤษในแบบของคุณ":"Practice English your way","Flashcard, Reading, Listening, Writing และแบบทดสอบในที่เดียว":"Flashcards, Reading, Listening, Writing, and mock exams in one place","แผนวันนี้":"Today's plan","นาที":"minutes","วัน":"days","เข้าสู่ระบบเพื่อบันทึกความคืบหน้า":"Sign in to save your progress","Sync ทุกอุปกรณ์ · ปลดล็อก Community และการนำเข้าชุด":"Sync across devices · unlock Community and set imports","ชุดที่คุณสร้างหรือนำเข้า →":"Sets you created or imported →","อันดับสัปดาห์นี้ →":"This week's ranking →","ดูสถิติการเรียนทั้งหมด →":"See all learning stats →","ฝึกทักษะ":"Practice skills","คลังของฉัน":"My Library","ทบทวนคำศัพท์":"Review vocabulary","เริ่มจากทักษะที่คุณเลือกไว้ แล้วกลับมาทบทวนต่อได้ทุกวัน":"Start with your chosen skill and return to review every day","เริ่มแผนวันนี้":"Start today's plan","ความก้าวหน้ารวม":"Total progress","ยังไม่ได้เช็คอินวันนี้":"Not checked in today","ชุด":"sets","เลือกชุดแล้วเริ่มฝึกได้ทันที":"Choose a set and start practicing","เริ่มฝึก":"Start practicing","วนคำจนจำครบ":"Loop words until mastered","จับคู่แข่งกับเวลาและทำลายสถิติ":"Race the clock and beat your record","เติมคำศัพท์ลงตารางไขว้จริง":"Complete a real crossword grid","อ่าน แตะคำ แปล และเก็บศัพท์":"Read, tap, translate, and save words","ฟังบทสนทนาและตอบคำถาม":"Listen to conversations and answer questions","Text Completion และเรียงย่อหน้า":"Text completion and paragraph organization","สร้างและเลือกชุดข้อสอบ":"Create and choose mock exams","ค้นหาชุดจากผู้ใช้อื่น":"Find sets from other learners","เช็คอินรายวัน":"Daily check-in","เช็คอินเพื่อรักษา Streak และรับ XP":"Check in to keep your streak and earn XP","เช็คอิน +20 XP":"Check in +20 XP","เปิด":"Open",
 "บัญชีของฉัน":"My account","เลือกหัวข้อที่ต้องการจัดการ":"Choose what you want to manage","โปรไฟล์":"Profile","ชื่อ รูปภาพ และกิจกรรมการเรียน":"Name, photo, and learning activity","แพ็กเกจและการชำระเงิน":"Plan and billing","ดูสิทธิ์ อัปเกรด หรือจัดการสมาชิก":"View benefits, upgrade, or manage membership","การตั้งค่า":"Settings","ภาษา ธีม และเสียง":"Language, theme, and sound","ข้อมูลและความเป็นส่วนตัว":"Data and privacy","ดาวน์โหลดข้อมูลหรือจัดการบัญชี":"Download data or manage your account","ย้อนกลับ":"Back","บัญชี":"Account",
 "ภาษา":"Language","เลือกภาษาของส่วนติดต่อผู้ใช้":"Choose the interface language","ภาษาที่แสดง":"Display language","สกุลเงินกำหนดอัตโนมัติ: ภาษาไทยใช้ THB และภาษาอื่นใช้ USD":"Currency is selected automatically: Thai uses THB and other languages use USD","ธีม":"Theme","เลือกหน้าตาของ Jumsup":"Choose how Jumsup looks","เลือกโหมดที่สบายตา":"Choose a comfortable appearance","สว่าง":"Light","มืด":"Dark","ตามระบบ":"System","เสียง":"Sound","เปิดหรือปิดเสียงตอบสนอง":"Turn feedback sounds on or off","เสียงเอฟเฟกต์":"Sound effects","เปิด":"Open","ปิด":"Off","เปิดเสียงอ่านคำศัพท์และเสียงตอบรับ":"Enable word pronunciation and feedback sounds",
 "เลือกแพ็กเกจที่เหมาะกับคุณ":"Choose the plan that fits you","เริ่มใช้ฟรีได้จริง และอัปเกรดเมื่ออยากฝึกได้มากขึ้น":"Start free and upgrade when you need more practice","เรียนต่อเนื่องในราคาที่เข้าถึงได้":"Keep learning at an accessible price","ราคาจะแสดงเป็น USD ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"Prices are shown in USD for your selected language and match Stripe Checkout","ราคาจะแสดงเป็น THB ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"Prices are shown in THB for your selected language and match Stripe Checkout","เริ่มต้น":"Starter","แพ็กเกจปัจจุบัน":"Current plan","ตลอดไป":"forever","คุ้มที่สุด":"Best value","รายปี":"Yearly","เฉลี่ย":"Equivalent to","เดือน":"month","ประหยัดประมาณ 33%":"save about 33%","ยืดหยุ่น":"Flexible","เหมาะสำหรับลองใช้ Pro ก่อน":"A flexible way to try Pro","ใช้งาน Free อยู่":"Current Free plan","จัดการสมาชิก":"Manage membership","เลือก Pro รายปี":"Choose yearly Pro","เลือก Pro รายเดือน":"Choose monthly Pro","เข้าสู่ระบบเพื่อเลือกแพ็กเกจ":"Sign in to choose a plan","คำถามสำคัญ":"Important questions","ยอดที่ถูกตัดจะตรงกับหน้าเว็บไหม?":"Will the charged amount match the website?","ยกเลิกแล้วข้อมูลหายไหม?":"Will I lose my data after cancelling?","ระบบจะเก็บเงินจริงหรือไม่?":"Will I be charged real money?",
 "เลือกชุดก่อนเข้าสู่หน้าฝึกจริง หรือสร้างชุดของคุณเอง":"Choose a set before starting, or create your own","สร้างชุดใหม่":"Create new set","นำเข้าจาก CSV":"Import CSV","เริ่มฝึก":"Start practice","แก้ไข":"Edit","ลบ":"Delete","ส่วนตัว":"Private","สาธารณะ":"Public","ยังไม่มีชุดฝึกในหมวดนี้":"No practice sets in this category yet","สร้างโดย":"Created by","ข้อ":"questions","ตอบแล้ว":"Answered","ส่งคำตอบ":"Submit answers","เวลาคงเหลือ":"Time remaining","ส่งข้อสอบ":"Submit exam","เปิด Transcript สำหรับโหมดฝึก":"Show transcript for practice mode","ฟังส่วนนี้":"Play this section","ฟังทั้งหมด":"Play all","พัก":"Pause","ต่อ":"Resume","หยุด":"Stop","สำเนียง":"Accent","ความเร็ว":"Speed","คำตอบที่ถูก":"Correct answer","ถูก":"Correct","ผิด":"Incorrect","ไม่ได้ตอบ":"Not answered","ทำอีกครั้ง":"Try again","กลับไปเลือกชุด":"Back to sets","คะแนน":"Score","ทำได้ดี":"Great job","ใกล้ถึงเป้าหมาย":"Almost there","ควรทบทวน":"Needs review",
 "เรียน Flashcards, Match และ Crossword ได้ไม่จำกัด":"Unlimited Flashcards, Match, and Crossword practice","ทดลอง Pro ฟรี 7 วันเมื่อสมัครใหม่":"7-day Pro trial for new sign-ups","Flashcard สูงสุด 100 คำต่อชุด และสร้างเองได้ 5 ชุด":"Up to 100 words per Flashcard set, and create up to 5 of your own","เก็บชุดจาก Community ได้พร้อมกัน 5 ชุด":"Keep up to 5 Community sets at a time","ทบทวนคำศัพท์ (SRS) ได้ไม่จำกัด":"Unlimited vocabulary review (SRS)","เช็คอิน Streak และลีดเดอร์บอร์ดครบทุกอย่าง":"Full daily check-in, streak, and leaderboard","Match 10 รอบ และ Crossword 3 รอบต่อวัน":"10 Match and 3 Crossword rounds per day","ฝึก Reading, Listening, Writing และ Mock วันละ 1 ชุดต่อประเภท":"1 Reading, Listening, Writing, and Mock set per day each","คลังแปลออฟไลน์ไม่จำกัด":"Unlimited offline translation library","สร้างและเก็บชุดได้ไม่จำกัด สูงสุด 1,000 คำต่อชุด":"Unlimited sets, up to 1,000 words each","Stripe · ชำระเงินจริงอย่างปลอดภัยผ่าน Stripe":"Stripe · Secure real payments through Stripe","ปี":"year","เก็บชุดคำศัพท์ส่วนตัว 3 ชุด":"Keep 3 private vocabulary sets","เก็บชุด Reading, Listening, Writing และ Mock ส่วนตัวอย่างละ 1 ชุด":"Keep 1 private set for each practice skill","แปลคำศัพท์ 10 คำต่อวัน":"Translate 10 words per day","Listening, Writing และ Mock อย่างละ 1 รอบต่อวัน":"1 Listening, Writing, and Mock session per day","ใช้งานและแชร์ชุดใน Community":"Use and share Community sets","เก็บชุดส่วนตัวได้ไม่จำกัด":"Unlimited private sets","แปลคำศัพท์ 100 คำต่อวัน":"Translate 100 words per day","ฝึก Reading, Listening, Writing และ Mock ได้ไม่จำกัด":"Unlimited Reading, Writing, Listening, and Mock practice","นำเข้า CSV ได้สูงสุด 1,000 แถวต่อครั้ง":"Import up to 1,000 CSV rows at a time","สถิติการเรียนและจุดอ่อนแบบละเอียด":"Detailed progress and weak-point insights","ยกเลิกได้ทุกเมื่อ สิทธิ์อยู่ถึงวันสิ้นรอบ":"Cancel anytime; access continues until the billing period ends","สิทธิ์ Pro ครบทุกอย่างเหมือนรายเดือน":"All Pro benefits included","ประหยัดเมื่อเทียบกับการชำระรายเดือน":"Save compared with monthly billing","ฝึกทุกทักษะและ Mock ได้ไม่จำกัด":"Unlimited practice and mock exams","ตรงกัน ระบบส่งทั้งแพ็กเกจและสกุลเงินที่เลือกไป Stripe Checkout หากสกุลเงินนั้นยังไม่พร้อม ระบบจะหยุดและไม่สร้างรายการชำระเงิน":"Yes. The plan and language-based currency are sent together to Stripe Checkout. If unavailable, checkout stops safely.","ไม่หาย ชุดและความคืบหน้ายังอยู่ แต่จะสร้างชุดส่วนตัวเพิ่มหรือเริ่มรอบที่เกินโควตา Free ไม่ได้จนกว่าจะลดจำนวนหรือสมัคร Pro อีกครั้ง":"No. Your sets and progress remain, but Free limits apply until you upgrade again.","Stripe Live · ชำระเงินจริงอย่างปลอดภัยผ่าน Stripe":"Stripe Live · Secure real payments through Stripe","ระบบจะเรียกเก็บเงินจริงเมื่อคุณตรวจสอบราคาและยืนยันการชำระเงินใน Stripe Checkout เท่านั้น":"You are charged only after reviewing the price and confirming payment in Stripe Checkout.",
 "ฟีเจอร์":"Features","ราคา":"Pricing","เข้าสู่ระบบ":"Sign in","ฝึกอังกฤษครบทั้ง":"Complete English practice for","ศัพท์ ทักษะ และข้อสอบ":"vocabulary, skills, and exams","วางแผนฝึกจากจุดอ่อนของคุณ ทบทวนศัพท์ด้วย Loop และลองข้อสอบคู่ขนานที่สร้างใหม่โดยไม่คัดลอกข้อสอบจริง":"Plan your practice around your weak points, review vocabulary with Loop, and try original parallel exams that never copy real test material.","เริ่มฝึกฟรี":"Start free","สมัครฟรี · รับ Pro 7 วัน":"Sign up free · 7 days of Pro","สมัครฟรี รับ Pro 7 วัน":"Sign up free, 7 days of Pro","ลองตัวอย่าง":"Try a demo","ไม่ต้องใช้บัตร":"No card required","มีแพ็กเกจฟรี":"Free plan available","ใช้ได้บนมือถือ":"Works on mobile","ยกเลิก":"Cancel","บันทึก":"Save","ตกลง":"OK","ลบถาวร":"Delete permanently","ค้นหา":"Search","ใหม่ล่าสุด":"Newest","ยอดนิยม":"Popular","คะแนนสูงสุด":"Top rated","ยังไม่พบผลลัพธ์":"No results found","ชุดที่พบ":"sets found","เพิ่มเนื้อหา":"Add content","เนื้อหาของฉัน":"My content",
 "กรุณาเข้าสู่ระบบก่อน":"Please sign in first","นิกเนมยาวได้ไม่เกิน 40 ตัว":"Nickname can be up to 40 characters","เปลี่ยนนิกเนมไม่สำเร็จ":"Could not change nickname","ชื่อนี้ถูกใช้แล้ว":"That name is already taken","ใช้ a–z, 0–9, _ หรือ . ยาว 3–20 ตัว":"Use a–z, 0–9, _ or ., 3–20 characters","กรุณาเข้าสู่ระบบใหม่":"Please sign in again","เปลี่ยนชื่อไม่สำเร็จ":"Could not change name","บันทึกไม่สำเร็จ":"Could not save","แลก Gift Code สำเร็จ":"Gift code redeemed","แลกโค้ดไม่สำเร็จ":"Could not redeem code","ใช้ Referral สำเร็จ":"Referral applied","ใช้โค้ดไม่สำเร็จ":"Could not apply code","ดาวน์โหลดข้อมูลไม่สำเร็จ":"Could not download your data","ส่งคำขอไม่สำเร็จ":"Could not send request","ส่งคำขอคืนเงินแล้ว ผู้ดูแลจะตรวจสอบก่อนดำเนินการ":"Refund request sent; an admin will review it before processing","ส่งคำขอคืนเงินไม่สำเร็จ":"Could not send refund request","อัปโหลดรูปไม่สำเร็จ":"Could not upload image","เข้าสู่ระบบไม่สำเร็จ":"Could not sign in","ออกจากระบบไม่สำเร็จ":"Could not sign out","เปิดหน้าชำระเงินไม่สำเร็จ":"Could not open checkout","เปิดหน้าจัดการสมาชิกไม่สำเร็จ":"Could not open the membership portal",
 "ระบบให้คะแนน/ถูกใจของ Community ยังไม่พร้อมใช้งาน (ผู้ดูแลต้องตั้งค่าฐานข้อมูลเพิ่ม)":"Community rating and likes are not available yet (an admin still needs to finish the database setup)","ทำรายการไม่สำเร็จ":"Action failed","นำเข้าเป็นสำเนาใหม่ในโหมดทดสอบแล้ว":"Imported as a new copy in test mode","กรุณาเข้าสู่ระบบก่อนนำเข้า Community":"Please sign in before importing from Community","นำเข้าชุดทางการของ Jumsup แล้ว":"Jumsup official set imported","เก็บชุด Community ครบ 3 ชุดแล้ว":"You already have 3 Community sets","ลบชุด Community เดิมก่อนเลือกชุดใหม่ หรืออัปเกรดเป็น Pro เพื่อเก็บได้ไม่จำกัด":"Remove an existing Community set before adding a new one, or upgrade to Pro for unlimited","นำเข้าเป็นสำเนาใหม่แล้ว":"Imported as a new copy","กรุณาเข้าสู่ระบบก่อนกดถูกใจ":"Please sign in before liking","กรุณาเข้าสู่ระบบก่อนให้คะแนน":"Please sign in before rating","บันทึกรีวิวแล้ว":"Review saved","ลบรีวิวแล้ว":"Review deleted","เข้าสู่ระบบเพื่อโหวต":"Sign in to vote","ตอบกลับแล้ว":"Reply posted","ลบคำตอบกลับแล้ว":"Reply deleted","กรุณาเข้าสู่ระบบก่อนรายงานเนื้อหา":"Please sign in before reporting content","ส่งรายงานให้ผู้ดูแลตรวจสอบแล้ว":"Report sent to the moderators",
 "Free เล่น Match ได้ 10 รอบต่อวัน อัปเกรดเป็น Pro เพื่อเล่นได้ไม่จำกัด":"Free plays 10 Match rounds per day; upgrade to Pro for unlimited","Free เล่น Crossword ได้ 3 รอบต่อวัน อัปเกรดเป็น Pro เพื่อเล่นได้ไม่จำกัด":"Free plays 3 Crossword rounds per day; upgrade to Pro for unlimited","เริ่มเกมไม่สำเร็จ":"Could not start the game","กรุณาเข้าสู่ระบบก่อนสร้างแผน":"Please sign in before creating a plan","วันสอบต้องเป็นวันนี้หรือหลังจากนี้":"The exam date must be today or later","เวลาต่อวันต้องเป็น 5, 10 หรือ 20 นาที":"Time per day must be 5, 10, or 20 minutes","บันทึกแผนไม่สำเร็จ":"Could not save your plan","ไม่พบชุดฝึกนี้":"Practice set not found","เริ่มแบบฝึกไม่สำเร็จ":"Could not start the exercise","เช็คอินไม่สำเร็จ":"Check-in failed","คำศัพท์ในชุดเต็มแล้ว":"This set is full",
 "เกม Match":"Match game","เกม Crossword":"Crossword game","แบบฝึก Reading":"Reading practice","แบบฝึก Listening":"Listening practice","แบบฝึก Writing":"Writing practice","ข้อสอบ Mock":"Mock exam","ผลการฝึก":"Practice results","สถิติการเรียน":"Learning stats","ลีดเดอร์บอร์ด":"Leaderboard","ฟีเจอร์นี้":"this feature","สมัครฟรี":"Sign up free","สมัครฟรีด้วย Google เพื่อเริ่มใช้ Jumsup เก็บความคืบหน้า สะสม XP/Streak และรับ Pro 7 วันทันที":"Sign up free with Google to start using Jumsup: save your progress, build XP and streaks, and get 7 days of Pro right away","Flashcard, Reading, Listening, Writing, Mock, เกม, ลีดเดอร์บอร์ด และ Community ใช้ได้เมื่อสมัคร เพื่อบันทึกผลและซิงก์ทุกอุปกรณ์":"Flashcards, Reading, Listening, Writing, Mock, games, the leaderboard, and Community are available once you sign up, so your results save and sync across devices","สมัครฟรีด้วย Google · รับ Pro 7 วัน":"Sign up free with Google · get 7 days of Pro","สมัครฟรีด้วย Google":"Continue free with Google",
 "correct_answer ต้องเป็น A, B, C หรือ D":"correct_answer must be A, B, C, or D","เบราว์เซอร์นี้ไม่รองรับการแจ้งเตือน":"This browser does not support notifications","ยังไม่ได้อนุญาตการแจ้งเตือน":"Notifications are not allowed yet","พรุ่งนี้":"tomorrow","ในไม่กี่นาที":"in a few minutes","พร้อมทบทวนแล้ว":"ready for review","ทั่วไป / CEFR":"General / CEFR","กลาง":"Intermediate","สูง":"Advanced",
 "แผนการเรียน":"Study plan","เป้าหมาย วันสอบ เวลาต่อวัน และทักษะที่เน้น":"Goals, exam dates, daily time, and focus skills","ความก้าวหน้าและคำที่ยังไม่แม่น":"Progress and words you haven't mastered","ชุดที่คุณสร้างหรือนำเข้า":"Sets you created or imported","แผงควบคุมแอดมิน":"Admin console","เปิดในแท็บใหม่ · ต้องล็อกอินบัญชีแอดมินอีกครั้ง":"Opens in a new tab · sign in again with your admin account","เข้ากลุ่ม LINE OpenChat":"Join the LINE OpenChat group","ถามข้อสอบ แชร์เทคนิค และหาเพื่อนติวกับผู้ใช้ Jumsup คนอื่น":"Ask exam questions, share tips, and find study partners among other Jumsup users","ออกจากระบบ":"Sign out",
 "ขอคืนเงิน":"Request a refund","กรุณาอธิบายเหตุผลอย่างน้อย 5 ตัวอักษร":"Please give a reason of at least 5 characters","การยกเลิก การชำระเงิน หรือรายการที่ไม่ถูกต้อง":"Cancellations, payments, or incorrect charges","ความช่วยเหลือด้านการชำระเงิน":"Billing help","ส่งคำขอ":"Send request","เหตุผลในการขอคืนเงิน":"Reason for the refund request","ถ้าเป็นการคืนเต็มจำนวน ให้ยกเลิกสมาชิกที่เกี่ยวข้องด้วย":"For a full refund, also cancel the related membership",
 "เข้าสู่ระบบเพื่อจัดการข้อมูลบัญชีของคุณ":"Sign in to manage your account data","ข้อมูลของคุณจัดเก็บไว้ในบัญชี":"Your data is stored in your account","ข้อมูลการเรียนและชุดที่สร้างจะ Sync อย่างปลอดภัย และไม่แสดงอีเมลต่อผู้ใช้อื่น":"Your learning data and sets sync securely, and your email is never shown to other users","ดาวน์โหลดข้อมูลของฉัน (JSON)":"Download my data (JSON)","ลบบัญชี":"Delete account","มีช่วงรอ 7 วันก่อนดำเนินการ":"There is a 7-day waiting period before it takes effect","ขอลบบัญชี":"Request account deletion",
 "แก้ไขนิกเนม":"Edit nickname","ตั้งนิกเนม":"Set a nickname","ชื่อที่อยากให้คนอื่นเห็น":"The name others will see","บันทึกนิกเนมแล้ว":"Nickname saved","กำลังตรวจสอบ…":"Checking…","ใช้ชื่อนี้ได้":"This name is available","เปลี่ยนชื่อแล้ว":"Name changed","กรอกโค้ด":"Enter a code","โค้ดผู้ชวน":"Referrer's code","แก้ไขชื่อ":"Edit name","ข้อมูลตอนนี้อยู่บนอุปกรณ์นี้":"Your data is currently on this device","นิกเนม":"Nickname","ชื่อที่คนอื่นเห็น · ซ้ำกันได้ · ใส่ภาษาไทย/อีโมจิได้":"The name others see · can repeat · Thai and emoji allowed","ยูเซอร์เนม":"Username","ตัวตนของคุณ (@handle) · ต้องไม่ซ้ำใคร · a–z 0–9 _ . ยาว 3–20":"Your identity (@handle) · must be unique · a–z 0–9 _ . 3–20 characters","เปลี่ยนรูป":"Change photo","แลกโค้ดเพื่อรับสิทธิ์ Pro":"Redeem a code for Pro","แลกโค้ด":"Redeem code","ชวนเพื่อน":"Invite friends","คนชวน +14 วัน · คนถูกชวน +7 วัน":"Inviter +14 days · invitee +7 days","ใช้โค้ด":"Apply code","โค้ดของคุณ:":"Your code:",
 "เปิดการแจ้งเตือนแล้ว":"Notifications turned on","ตั้งค่าการแจ้งเตือนไม่สำเร็จ":"Could not update notification settings","เข้าสู่ระบบก่อนจึงจะเปิดได้":"Sign in first to enable this","เบราว์เซอร์นี้ไม่รองรับ":"Not supported in this browser","เปิดอยู่":"On","ปิดอยู่":"Off","แจ้งเตือน":"Notifications","การแจ้งเตือน":"Notifications","เตือนก่อน Streak หลุด และแจ้งเมื่อสรุปอันดับรายสัปดาห์พร้อม":"Remind me before my streak breaks and when the weekly ranking summary is ready","แจ้งเตือนบนอุปกรณ์นี้":"Notifications on this device",
 "ประเภทข้อสอบ":"Exam type","ทักษะ":"Skill","ระดับ":"Level","— ไม่ระบุ —":"— Not specified —",
 "ค้นหาชื่อชุด หรือ username ผู้สร้าง…":"Search by set name or creator username…","ทั้งหมด":"All","คัดลอกลิงก์แชร์แล้ว":"Share link copied","เข้ากลุ่ม LINE OpenChat ของ Jumsup":"Join Jumsup's LINE OpenChat group","ถามข้อสอบ แชร์เทคนิค และหาเพื่อนติว":"Ask exam questions, share tips, and find study partners","ทุกข้อสอบ":"All exams","ให้คะแนน:":"Rate:","ดูตัวอย่าง":"Preview","แชร์":"Share",
 "โหลดตัวอย่างไม่สำเร็จ":"Could not load the preview","ตัวอย่างชุด":"Set preview","นำเข้าเข้าคลัง":"Import to my library","กำลังโหลดตัวอย่าง…":"Loading preview…",
 "รีวิวของคุณ":"Your review","เขียนรีวิว":"Write a review","บอกสิ่งที่เป็นประโยชน์กับผู้เรียนคนอื่น (ไม่บังคับ)":"Share what other learners would find helpful (optional)","บันทึกการแก้ไข":"Save changes","ส่งรีวิว":"Submit review","ไม่ระบุชื่อ":"Anonymous","แก้ไขคำตอบ":"Edit reply","ตอบกลับ":"Reply","ตอบกลับรีวิวนี้…":"Reply to this review…","รีวิวแบบไม่ระบุชื่อ (ผู้สร้างและผู้ใช้อื่นจะไม่เห็นชื่อคุณ)":"Review anonymously (the creator and other users won't see your name)","ลบรีวิว":"Delete review","เข้าสู่ระบบเพื่อเขียนรีวิว":"Sign in to write a review","ล่าสุด":"Newest","มีประโยชน์สุด":"Most helpful","กำลังโหลด…":"Loading…","ยังไม่มีรีวิว — เป็นคนแรกได้เลย":"No reviews yet — be the first","✓ นำเข้าแล้ว":"✓ Imported","ของคุณ":"Yours","ตอบกลับจากผู้สร้าง":"Reply from the creator","คำ":"words",
 "โหลดโปรไฟล์ไม่สำเร็จ":"Could not load the profile","ครีเอเตอร์":"Creator","ยังไม่มีชุดสาธารณะจากผู้ใช้นี้":"This user has no public sets yet","กลับไป Community":"Back to Community",
 "กรุณาตั้งชื่อชุด":"Please name the set","กรุณากรอกคำศัพท์ให้ครบทุกรายการ":"Please fill in every word","สร้าง Flashcard ครบ 3 ชุดแล้ว":"You already have 3 Flashcard sets","Free สร้างชุดของตัวเองได้สูงสุด 3 ชุด อัปเกรดเป็น Pro เพื่อสร้างได้ไม่จำกัด":"Free lets you create up to 3 of your own sets; upgrade to Pro for unlimited","คำศัพท์เกินจำนวนที่แพ็กเกจรองรับ":"More words than your plan allows","บันทึกชุดไม่สำเร็จ":"Could not save the set","เช่น คำศัพท์ A-Level บทที่ 1":"e.g. A-Level Vocabulary, Unit 1","คำหรือวลี เช่น analyze":"Word or phrase, e.g. analyze","คำอ่าน / การเน้นเสียง (ไม่บังคับ)":"Pronunciation / stress (optional)","ความหมาย เช่น วิเคราะห์":"Meaning, e.g. analyze","ประโยคตัวอย่าง (ไม่บังคับ)":"Example sentence (optional)","คำศัพท์ในชุด":"Words in this set","+ เพิ่มคำศัพท์":"+ Add word","Free เก็บ Flashcard ส่วนตัวได้ 3 ชุด ชุดนี้จะเป็น Public เฉพาะเมื่อคุณกดยืนยันเผยแพร่":"Free keeps 3 private Flashcard sets; this set becomes public only when you confirm publishing",
 "จับคู่คำศัพท์กับความหมาย — ต้องจำศัพท์ในชุดนั้นอย่างน้อย 4 คำ":"Match words to meanings — you need at least 4 learned words in the set","เติมคำไขว้จากคำที่จำแล้ว — ต้องจำอย่างน้อย 3 คำ":"Fill a crossword from your learned words — you need at least 3","แก้ไขชุด":"Edit set","ลบชุด":"Delete set","ทบทวนตามรอบช่วยให้จำได้นานขึ้น":"Spaced review helps you remember longer","ทบทวนทั้งหมด":"Review all","เริ่ม Flashcards":"Start Flashcards",
 "ฟังเสียง":"Play audio","บันทึกความก้าวหน้าไม่สำเร็จ":"Could not save progress","ไม่พบชุดคำศัพท์":"Vocabulary set not found","ทบทวนครบรอบนี้แล้ว":"You've finished this round","ยังไม่มีคำที่ครบกำหนดทบทวน":"No words are due for review yet","ทบทวนคำที่ครบกำหนด · จำได้ = เลื่อนออกไป · ยังไม่จำ = เจอใหม่รอบนี้":"Review words that are due · Know it = push it back · Still learning = see it again this round","แตะการ์ดเพื่อพลิกดูคำแปล · ปัดขวา = จำได้ · ปัดซ้าย = ยังไม่จำ":"Tap a card to flip it · swipe right = Know it · swipe left = Still learning","เหลือทบทวน":"left to review","เหลืออีก":"remaining","พลิกการ์ด":"Flip card","← ย้อนกลับ":"← Back","เพิ่มอีก 10 คำ":"Add 10 more words","⚙ ตั้งค่า":"⚙ Settings","คำศัพท์":"Word","แตะเพื่อพลิก":"Tap to flip","← ยังไม่จำ":"← Still learning","จำได้ →":"Know it →","เสร็จสิ้น":"Done","เสียงอ่าน":"Voice","ค่าเริ่มต้นของอุปกรณ์":"Device default","อุปกรณ์นี้ไม่มีเสียงภาษาอังกฤษให้เลือกเพิ่ม":"This device has no additional English voices","ความเร็วเสียง":"Speech speed","ทดลองฟัง":"Test voice","ช้ามาก (0.7×)":"Very slow (0.7×)","ช้า (0.8×)":"Slow (0.8×)","ปกติ (0.9×)":"Normal (0.9×)","เร็วขึ้น (1.0×)":"Faster (1.0×)","เร็ว (1.15×)":"Fast (1.15×)",
 "ยังเล่น Crossword ไม่ได้":"Crossword isn't available yet","คำที่จำแล้วต้องมีตัวอักษรร่วมกันอย่างน้อย 3 คำ — จำคำเพิ่มแล้วลองอีกครั้ง":"You need at least 3 learned words that share letters — learn more and try again","ไม่มีคำในแนวนี้":"No word in this direction","← ออกจากเกม":"← Leave game",
 "จับคู่คำศัพท์กับความหมายให้ครบเร็วที่สุด":"Match all the words to their meanings as fast as you can","พร้อมเล่นไหม?":"Ready to play?","เริ่มเกม":"Start game","จบเกม! 🎉":"Game over! 🎉","· ใช้":"· took","เล่นอีกครั้ง":"Play again","กลับ":"Back",
 "ทดลอง Pro หมดแล้ว — สมัคร Pro รายปี ฿99/เดือน หรือชวนเพื่อนสมัคร Pro รับ +14 วัน":"Your Pro trial has ended — get yearly Pro at ฿99/month, or invite a friend who subscribes to Pro for +14 days","โค้งสุดท้ายก่อนสอบ — Pro ปลดล็อก Reading / Listening / Writing / Mock ไม่จำกัด":"The home stretch before your exam — Pro unlocks unlimited Reading / Listening / Writing / Mock","เช็คอินแล้ววันนี้":"Checked in today","เสร็จ":"Done","เช็คอินรับ +20 XP และรักษา Streak":"Check in for +20 XP and keep your streak","เช็คอิน":"Check in","ทบทวน":"Review","เริ่ม":"Start","จับเวลาทำ Mock สักชุดก่อนสอบ":"Time yourself on a Mock before the exam","ทำ Mock":"Take a Mock","มาฝึกภาษาอังกฤษเตรียมสอบกับ Jumsup กัน — สมัครฟรีรับ Pro 7 วัน":"Come practice exam English with Jumsup — sign up free and get 7 days of Pro","คัดลอกลิงก์ชวนเพื่อนแล้ว":"Invite link copied","ก้าวต่อไป":"Next step","ตั้งค่าแผนการเรียนของคุณ":"Set up your study plan","ใช้เวลาไม่ถึง 1 นาที เพื่อให้ Jumsup แนะนำได้ตรงจุด":"Takes under a minute and helps Jumsup give better recommendations","เริ่มตั้งค่า":"Get started","แก้ไขแผน":"Edit plan","ตั้งวันสอบและทักษะที่อยากเน้น":"Set your exam dates and focus skills","รักษา Streak และรับ +20 XP":"Keep your streak and earn +20 XP","ยังไม่มีชุดของคุณเอง":"You don't have any sets yet","สร้างชุดคำศัพท์/ข้อสอบเอง นำเข้าจาก CSV หรือหยิบจาก Community มาใช้":"Create your own vocabulary or exam sets, import from CSV, or grab one from Community","ไปที่คลังของฉัน":"Go to My Library","เปิด Community":"Open Community","ชวนเพื่อน รับ Pro ฟรี":"Invite friends, get Pro free","เมื่อเพื่อนสมัคร Pro: คุณ +14 วัน · เพื่อน +7 วัน · ลิงก์กรอกโค้ดให้อัตโนมัติ":"When a friend subscribes to Pro: you +14 days · friend +7 days · the link fills in the code automatically","แชร์ลิงก์ชวนเพื่อน":"Share invite link",
 "ตอนนี้รองรับ CSV เท่านั้น กรุณาดาวน์โหลดเทมเพลต CSV":"Only CSV is supported right now; please download the CSV template","ไฟล์ไม่มีข้อมูล":"The file has no data","อ่านไฟล์ไม่สำเร็จ":"Could not read the file","ยังไม่มีรายการที่พร้อมนำเข้า":"Nothing is ready to import yet","ใช้ไฟล์ CSV UTF-8 ที่มีชื่อคอลัมน์ตามแม่แบบ":"Use a UTF-8 CSV file with column names matching the template","ยังไม่มีไฟล์ตามรูปแบบ?":"Don't have a file in the right format?","ระบบจะแสดงตัวอย่างให้ตรวจ และยังไม่บันทึกทันที":"You'll see a preview to check first; nothing is saved right away","ไม่ต้องนำเข้า":"Cancel import","ตรวจข้อมูลก่อนนำเข้า":"Review before importing","แถว":"Row","ปัญหา":"Issue","รายการที่มีปัญหาจะไม่ถูกนำเข้า คุณสามารถแก้ไฟล์แล้วเลือกใหม่ หรือดำเนินการเฉพาะรายการที่พร้อมได้":"Rows with problems won't be imported. You can fix the file and reselect it, or continue with only the valid rows.","พร้อมสร้างฉบับร่าง":"Ready to create a draft",
 "TCAS English · ออกบ่อย":"TCAS English · High-frequency","Jumsup — ฝึกอังกฤษให้เป็นระบบในแบบของคุณ":"Jumsup — build a consistent English routine your way","กลุ่ม LINE OpenChat":"LINE OpenChat group",
 "สัปดาห์นี้":"This week","โหลดอันดับไม่สำเร็จ":"Could not load the leaderboard","อันดับย้อนหลัง":"Past weeks","อันดับสัปดาห์นี้":"This week's ranking","แข่งสะสม XP รีเซ็ตทุกวันจันทร์":"Compete on XP; resets every Monday","สัปดาห์นั้น":"That week","สัปดาห์นั้นคุณยังไม่มี XP บนกระดาน":"You had no XP on the board that week","ยังไม่มี XP สัปดาห์นี้ — เช็คอินหรือเรียนสักหน่อยเพื่อขึ้นกระดาน":"No XP yet this week — check in or study a little to get on the board","ซ่อนชื่อ":"Hidden name","ไม่มีข้อมูลสัปดาห์นั้น":"No data for that week","ยังไม่มีใครทำคะแนนสัปดาห์นี้ — เป็นคนแรกเลย!":"No one has scored this week — be the first!","เข้าสู่ระบบเพื่อร่วมแข่ง":"Sign in to compete","สะสม XP จากเช็คอินและการเรียนเพื่อไต่อันดับ":"Earn XP from check-ins and studying to climb the ranks","กำลังโหลดอันดับ…":"Loading leaderboard…","ซ่อนชื่อของฉันบนกระดาน":"Hide my name on the board","(คุณ)":"(you)",
 "สัปดาห์แรกบนกระดาน":"Your first week on the board","อันดับเท่าสัปดาห์ก่อน":"Same rank as last week","สรุปสัปดาห์ที่ผ่านมา":"Last week's recap","ดูกระดาน":"View board","รับทราบ":"Got it","สะสมได้":"earned","ในสัปดาห์นั้น":"that week","สัปดาห์นี้ทำต่อให้ติดรางวัลนะ 💪":"Keep going this week to reach the rewards 💪",
 "คัดลอกลิงก์แชร์":"Copy share link","ชุดคำศัพท์และชุดฝึกทั้งหมดที่คุณสร้างหรือนำเข้า อยู่ที่เดียว":"All the vocabulary and practice sets you created or imported, in one place","เลือกประเภทชุดฝึก":"Choose a practice set type","+ ชุดคำศัพท์":"+ Vocabulary set","+ ชุดฝึกทักษะ":"+ Skill practice set","หาชุดเพิ่มจาก Community":"Find more sets in Community",
 "มกราคม":"January","กุมภาพันธ์":"February","มีนาคม":"March","เมษายน":"April","พฤษภาคม":"May","มิถุนายน":"June","กรกฎาคม":"July","สิงหาคม":"August","กันยายน":"September","ตุลาคม":"October","พฤศจิกายน":"November","ธันวาคม":"December","อา":"Sun","พฤ":"Thu","ตั้งวันสอบ (แตะเพื่อเลือก)":"Set an exam date (tap to choose)","ล้างวันที่":"Clear date","ก.พ. ภาค ก":"Feb · Part A","มีวันสอบที่เป็นวันที่ผ่านมาแล้ว":"One of your exam dates is in the past","แก้ไขแผนการเรียน":"Edit study plan","ตั้งค่าแผนการเรียน":"Set up your study plan","พิมพ์ชื่อการสอบเอง":"Type your own exam name","กำลังบันทึก…":"Saving…","บันทึกแผน":"Save plan","สร้างแผนของฉัน":"Create my plan","ให้ Jumsup รู้จักเป้าหมายของคุณ":"Tell Jumsup your goals","ใช้เวลาไม่ถึง 1 นาที และเปลี่ยนได้ภายหลังในหน้าบัญชี":"Takes under a minute, and you can change it later in your account","← กลับไปหน้าบัญชี":"← Back to account","คุณกำลังเตรียมสอบอะไรบ้าง?":"Which exams are you preparing for?","เพิ่มได้หลายรายการ กำหนดวันสอบของแต่ละอันแยกกัน (ไม่บังคับ)":"Add several; set a separate exam date for each (optional)","วันที่ผ่านมาแล้ว เลือกวันในอนาคต":"That date has passed; choose a future date","เพิ่ม":"Add","อยากฝึกวันละกี่นาที?":"How many minutes a day do you want to practice?","ตอนนี้อยากพัฒนาส่วนไหน?":"What do you want to improve right now?","เลือกได้มากกว่า 1 อย่าง":"Choose one or more",
 "Passage / คำสั่ง":"Passage / instructions","เนื้อหาประกอบ":"Supporting content","กรุณาตั้งชื่อชุดฝึก":"Please name the practice set","กรุณาเพิ่มอย่างน้อย 1 Section":"Please add at least 1 section","กรุณากรอกโจทย์และตัวเลือกอย่างน้อย 2 ตัวเลือกให้ครบ":"Please fill in the question and at least 2 options","บันทึกชุดฝึกไม่สำเร็จ":"Could not save the practice set","ชื่อ Section":"Section name","วางเนื้อหาของ Section นี้":"Paste this section's content","พิมพ์คำถาม":"Type a question","บันทึกชุดฝึก":"Save practice set","เวลารวม (นาที)":"Total time (minutes)","+ เพิ่ม Section":"+ Add section","ลบ Section":"Delete section","คำอธิบายคำตอบ (ไม่บังคับ)":"Answer explanation (optional)","+ เพิ่มคำถาม":"+ Add question",
 "← ออกจากแบบฝึก":"← Leave exercise","▶ ฟังทั้งหมด":"▶ Play all","‖ พัก":"‖ Pause","▶ ต่อ":"▶ Resume","■ หยุด":"■ Stop","▶ ฟังส่วนนี้":"▶ Play this section","เปิด Transcript":"Show transcript",
 "เลือกรอบใหม่จากหน้ารายการ ระบบจะตรวจสิทธิ์ทดลองหรือเวลาพักให้อัตโนมัติ":"Pick another round from the list; trial access and cooldowns are checked automatically","คัดลอกผลและลิงก์แล้ว":"Result and link copied","แชร์ผล":"Share result","Pro ฝึก Reading / Listening / Writing / Mock ได้ไม่จำกัด + วิเคราะห์จุดอ่อนแบบละเอียด":"Pro: unlimited Reading / Listening / Writing / Mock + detailed weak-point analysis","คำตอบที่ถูก:":"Correct answer:","บันทึกลงชุด":"Save to set",
 "ไม่พบชุดนี้ หรือถูกตั้งเป็นส่วนตัว":"This set was not found or is private","เปิดชุดนี้ไม่ได้":"Can't open this set","ไม่พบชุดนี้ หรือถูกตั้งเป็นส่วนตัว/ถูกซ่อน":"This set was not found, or is private/hidden","ชุดที่แชร์":"Shared set","คัดลอกลิงก์แล้ว":"Link copied","ไปที่ Community":"Go to Community","ดูรีวิว":"See reviews","คัดลอกลิงก์":"Copy link","สมัครฟรีเพื่อนำเข้า · รับ Pro 7 วัน":"Sign up free to import · get 7 days of Pro",
 "กราฟคะแนนย้อนหลัง":"Score history chart","ภาพรวมความก้าวหน้าและคำที่ยังต้องทบทวน":"An overview of your progress and words that still need review","ไม่มีชื่อ":"Untitled","XP รวม":"Total XP","จำแล้ว":"Learned","ผลสอบย้อนหลัง":"Past exam results","ยังไม่มีประวัติการทำข้อสอบ — ลองทำ Reading, Listening หรือ Mock สักรอบ":"No exam history yet — try a round of Reading, Listening, or Mock","สูงสุด":"Best","ความคืบหน้าแต่ละชุด":"Progress by set","ยังไม่มีชุดคำศัพท์ที่ฝึก":"No vocabulary sets practiced yet","คำที่ยังไม่แม่น":"Words to work on","ทบทวนชุดนี้ →":"Review this set →",
 "กำลังซิงก์…":"Syncing…","ใช้ธีมสว่าง":"Use light theme","ใช้ธีมมืด":"Use dark theme","ผู้ใช้":"User","ดู Jumsup Pro":"See Jumsup Pro","นำเข้า CSV":"Import CSV",
 "ออกจากแบบฝึก":"Leave exercise","ออกจากเกม":"Leave game","ย้อนกลับ":"Back","ตั้งค่า":"Settings","จบเกม!":"Game over!","นำเข้าแล้ว":"Imported","มีประโยชน์":"Helpful","เพิ่มแล้ว":"Added","+ เพิ่มเข้า Flashcard":"+ Add to Flashcards"
};
const ZH={
 "ฝึกภาษาอังกฤษในแบบของคุณ":"按自己的方式学习英语","Flashcard, Reading, Listening, Writing และแบบทดสอบในที่เดียว":"单词卡、阅读、听力、写作和模拟考试，一站完成","แผนวันนี้":"今日计划","นาที":"分钟","ทบทวนคำศัพท์":"复习词汇","เริ่มจากทักษะที่คุณเลือกไว้ แล้วกลับมาทบทวนต่อได้ทุกวัน":"从你选择的技能开始，每天回来复习","เริ่มแผนวันนี้":"开始今日计划","ความก้าวหน้ารวม":"总进度","ยังไม่ได้เช็คอินวันนี้":"今天尚未签到","ชุด":"套","เลือกชุดแล้วเริ่มฝึกได้ทันที":"选择一套即可开始练习","เริ่มฝึก":"开始练习","วนคำจนจำครบ":"循环复习直到掌握","จับคู่แข่งกับเวลาและทำลายสถิติ":"计时配对并刷新纪录","เติมคำศัพท์ลงตารางไขว้จริง":"完成真正的填字游戏","อ่าน แตะคำ แปล และเก็บศัพท์":"阅读、点击、翻译并收藏单词","ฟังบทสนทนาและตอบคำถาม":"听对话并回答问题","Text Completion และเรียงย่อหน้า":"文本填空与段落排序","สร้างและเลือกชุดข้อสอบ":"创建并选择模拟考试","ค้นหาชุดจากผู้ใช้อื่น":"查找其他学习者的内容","เช็คอินรายวัน":"每日签到","เช็คอินเพื่อรักษา Streak และรับ XP":"签到以保持连续记录并获得 XP","เช็คอิน +20 XP":"签到 +20 XP","เปิด":"打开",
 "บัญชีของฉัน":"我的账户","เลือกหัวข้อที่ต้องการจัดการ":"选择要管理的项目","โปรไฟล์":"个人资料","ชื่อ รูปภาพ และกิจกรรมการเรียน":"姓名、头像和学习活动","แพ็กเกจและการชำระเงิน":"套餐与付款","ดูสิทธิ์ อัปเกรด หรือจัดการสมาชิก":"查看权益、升级或管理会员","การตั้งค่า":"设置","ภาษา ธีม และเสียง":"语言、主题与声音","ข้อมูลและความเป็นส่วนตัว":"数据与隐私","ดาวน์โหลดข้อมูลหรือจัดการบัญชี":"下载数据或管理账户","ย้อนกลับ":"返回","บัญชี":"账户","ภาษา":"语言","เลือกภาษาของส่วนติดต่อผู้ใช้":"选择界面语言","ภาษาที่แสดง":"显示语言","สกุลเงินกำหนดอัตโนมัติ: ภาษาไทยใช้ THB และภาษาอื่นใช้ USD":"货币自动选择：泰语使用 THB，其他语言使用 USD","ธีม":"主题","เลือกหน้าตาของ Jumsup":"选择 Jumsup 的外观","เลือกโหมดที่สบายตา":"选择舒适的显示模式","สว่าง":"浅色","มืด":"深色","ตามระบบ":"跟随系统","เสียง":"声音","เปิดหรือปิดเสียงตอบสนอง":"开启或关闭反馈音效","เสียงเอฟเฟกต์":"音效","เปิด":"打开","ปิด":"关闭","เปิดเสียงอ่านคำศัพท์และเสียงตอบรับ":"启用单词发音和反馈音效",
 "เลือกแพ็กเกจที่เหมาะกับคุณ":"选择适合你的套餐","เริ่มใช้ฟรีได้จริง และอัปเกรดเมื่ออยากฝึกได้มากขึ้น":"免费开始，需要更多练习时再升级","เรียนต่อเนื่องในราคาที่เข้าถึงได้":"以合理价格持续学习","ราคาจะแสดงเป็น USD ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"价格将按所选语言显示为 USD，并与 Stripe 结账页一致","ราคาจะแสดงเป็น THB ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"价格将显示为 THB，并与 Stripe 结账页一致","เริ่มต้น":"入门","แพ็กเกจปัจจุบัน":"当前套餐","ตลอดไป":"永久","คุ้มที่สุด":"最划算","รายปี":"年付","เฉลี่ย":"平均","เดือน":"月","ประหยัดประมาณ 33%":"约省 33%","ยืดหยุ่น":"灵活","เหมาะสำหรับลองใช้ Pro ก่อน":"适合先体验 Pro","ใช้งาน Free อยู่":"正在使用免费版","จัดการสมาชิก":"管理会员","เลือก Pro รายปี":"选择 Pro 年付","เลือก Pro รายเดือน":"选择 Pro 月付","เข้าสู่ระบบเพื่อเลือกแพ็กเกจ":"登录后选择套餐","คำถามสำคัญ":"常见问题","ยอดที่ถูกตัดจะตรงกับหน้าเว็บไหม?":"扣款金额会与网站一致吗？","ยกเลิกแล้วข้อมูลหายไหม?":"取消后数据会丢失吗？","ระบบจะเก็บเงินจริงหรือไม่?":"现在会真实扣款吗？",
 "选择ชุดก่อนเข้าสู่หน้าฝึกจริง หรือสร้างชุดของคุณเอง":"选择内容后开始练习，或创建自己的内容","สร้างชุดใหม่":"新建内容","นำเข้าจาก CSV":"从 CSV 导入","เริ่มฝึก":"开始练习","แก้ไข":"编辑","ลบ":"删除","ส่วนตัว":"私密","สาธารณะ":"公开","ยังไม่มีชุดฝึกในหมวดนี้":"此分类暂无练习内容","สร้างโดย":"创建者","ข้อ":"题","ตอบแล้ว":"已回答","ส่งคำตอบ":"提交答案","เวลาคงเหลือ":"剩余时间","ส่งข้อสอบ":"提交考试","เปิด Transcript สำหรับโหมดฝึก":"显示练习模式文字稿","ฟังส่วนนี้":"播放本段","ฟังทั้งหมด":"全部播放","พัก":"暂停","ต่อ":"继续","หยุด":"停止","สำเนียง":"口音","ความเร็ว":"速度","คำตอบที่ถูก":"正确答案","ถูก":"正确","ผิด":"错误","ไม่ได้ตอบ":"未回答","ทำอีกครั้ง":"再试一次","กลับไปเลือกชุด":"返回内容列表","คะแนน":"分数","ทำได้ดี":"做得很好","ใกล้ถึงเป้าหมาย":"接近目标","ควรทบทวน":"需要复习",
 "เรียน Flashcards, Match และ Crossword ได้ไม่จำกัด":"无限练习单词卡、配对和填字游戏","เก็บชุดคำศัพท์ส่วนตัว 3 ชุด":"保存 3 套私密词汇","เก็บชุด Reading, Listening, Writing และ Mock ส่วนตัวอย่างละ 1 ชุด":"每种技能可保存 1 套私密练习","แปลคำศัพท์ 10 คำต่อวัน":"每天翻译 10 个单词","Listening, Writing และ Mock อย่างละ 1 รอบต่อวัน":"每天各 1 次听力、写作和模拟考试","ใช้งานและแชร์ชุดใน Community":"使用并分享社区内容","เก็บชุดส่วนตัวได้ไม่จำกัด":"无限保存私密内容","แปลคำศัพท์ 100 คำต่อวัน":"每天翻译 100 个单词","ฝึก Reading, Listening, Writing และ Mock ได้ไม่จำกัด":"无限练习阅读、听力、写作和模拟考试","นำเข้า CSV ได้สูงสุด 1,000 แถวต่อครั้ง":"每次最多导入 1,000 行 CSV","สถิติการเรียนและจุดอ่อนแบบละเอียด":"详细学习统计与薄弱点分析","ยกเลิกได้ทุกเมื่อ สิทธิ์อยู่ถึงวันสิ้นรอบ":"可随时取消，权益持续到计费周期结束","สิทธิ์ Pro ครบทุกอย่างเหมือนรายเดือน":"包含全部 Pro 权益","ประหยัดเมื่อเทียบกับการชำระรายเดือน":"比月付更省","ฝึกทุกทักษะและ Mock ได้ไม่จำกัด":"无限技能练习和模拟考试","ฟีเจอร์":"功能","ราคา":"价格","เข้าสู่ระบบ":"登录","เริ่มฝึกฟรี":"免费开始","ลองตัวอย่าง":"试用示例","ยกเลิก":"取消","บันทึก":"保存","ตกลง":"确定","ลบถาวร":"永久删除","ค้นหา":"搜索","ใหม่ล่าสุด":"最新","ยอดนิยม":"热门","คะแนนสูงสุด":"评分最高","ยังไม่พบผลลัพธ์":"未找到结果","ชุดที่พบ":"套内容","เพิ่มเนื้อหา":"添加内容","เนื้อหาของฉัน":"我的内容","เลือกชุดก่อนเข้าสู่หน้าฝึกจริง หรือสร้างชุดของคุณเอง":"选择内容后开始练习，或创建自己的内容"
};

const LOCALIZED={
 ja:{"Practice English your way":"自分らしく英語を練習","Today's plan":"今日のプラン","Review vocabulary":"単語を復習","Start today's plan":"今日のプランを開始","Total progress":"総合進捗","Not checked in today":"今日はまだチェックインしていません","Start practicing":"練習を始める","Daily check-in":"毎日のチェックイン","Open":"開く","My account":"マイアカウント","Choose what you want to manage":"管理する項目を選択","Profile":"プロフィール","Plan and billing":"プランとお支払い","Settings":"設定","Data and privacy":"データとプライバシー","Language":"言語","Choose the interface language":"表示言語を選択","Display language":"表示言語","Currency is selected automatically: Thai uses THB and other languages use USD":"通貨は自動選択されます：タイ語はTHB、その他はUSD","Theme":"テーマ","Light":"ライト","Dark":"ダーク","Sound":"サウンド","Choose the plan that fits you":"あなたに合うプランを選択","Keep learning at an accessible price":"手頃な価格で学習を継続","Starter":"スターター","Current plan":"現在のプラン","Best value":"最もお得","Yearly":"年間","Flexible":"フレキシブル","Manage membership":"メンバーシップ管理","Important questions":"よくある質問","Create new set":"新しいセット","Import CSV":"CSVをインポート","Edit":"編集","Delete":"削除","Private":"非公開","Public":"公開","Submit answers":"回答を提出","Time remaining":"残り時間","Correct":"正解","Incorrect":"不正解","Cancel":"キャンセル","Save":"保存","Search":"検索","Popular":"人気","Newest":"新着"},
 ko:{"Practice English your way":"나만의 방식으로 영어 연습","Today's plan":"오늘의 계획","Review vocabulary":"어휘 복습","Start today's plan":"오늘의 계획 시작","Total progress":"전체 진행률","Not checked in today":"오늘 아직 체크인하지 않음","Start practicing":"연습 시작","Daily check-in":"매일 체크인","Open":"열기","My account":"내 계정","Choose what you want to manage":"관리할 항목을 선택하세요","Profile":"프로필","Plan and billing":"요금제 및 결제","Settings":"설정","Data and privacy":"데이터 및 개인정보","Language":"언어","Choose the interface language":"인터페이스 언어 선택","Display language":"표시 언어","Currency is selected automatically: Thai uses THB and other languages use USD":"통화는 자동 선택됩니다. 태국어는 THB, 그 외 언어는 USD","Theme":"테마","Light":"라이트","Dark":"다크","Sound":"소리","Choose the plan that fits you":"나에게 맞는 요금제 선택","Keep learning at an accessible price":"합리적인 가격으로 계속 학습","Starter":"시작","Current plan":"현재 요금제","Best value":"가장 경제적","Yearly":"연간","Flexible":"유연한 선택","Manage membership":"멤버십 관리","Important questions":"자주 묻는 질문","Create new set":"새 세트 만들기","Import CSV":"CSV 가져오기","Edit":"수정","Delete":"삭제","Private":"비공개","Public":"공개","Submit answers":"답안 제출","Time remaining":"남은 시간","Correct":"정답","Incorrect":"오답","Cancel":"취소","Save":"저장","Search":"검색","Popular":"인기","Newest":"최신"},
 pt:{"Practice English your way":"Pratique inglês do seu jeito","Today's plan":"Plano de hoje","Review vocabulary":"Revisar vocabulário","Start today's plan":"Iniciar plano de hoje","Total progress":"Progresso total","Not checked in today":"Ainda não fez check-in hoje","Start practicing":"Começar a praticar","Daily check-in":"Check-in diário","Open":"Abrir","My account":"Minha conta","Choose what you want to manage":"Escolha o que deseja gerenciar","Profile":"Perfil","Plan and billing":"Plano e cobrança","Settings":"Configurações","Data and privacy":"Dados e privacidade","Language":"Idioma","Choose the interface language":"Escolha o idioma da interface","Display language":"Idioma de exibição","Currency is selected automatically: Thai uses THB and other languages use USD":"A moeda é automática: tailandês usa THB e os demais idiomas usam USD","Theme":"Tema","Light":"Claro","Dark":"Escuro","Sound":"Som","Choose the plan that fits you":"Escolha o plano ideal","Keep learning at an accessible price":"Continue aprendendo por um preço acessível","Starter":"Inicial","Current plan":"Plano atual","Best value":"Melhor custo-benefício","Yearly":"Anual","Flexible":"Flexível","Manage membership":"Gerenciar assinatura","Important questions":"Perguntas importantes","Create new set":"Criar conjunto","Import CSV":"Importar CSV","Edit":"Editar","Delete":"Excluir","Private":"Privado","Public":"Público","Submit answers":"Enviar respostas","Time remaining":"Tempo restante","Correct":"Correto","Incorrect":"Incorreto","Cancel":"Cancelar","Save":"Salvar","Search":"Buscar","Popular":"Popular","Newest":"Mais recentes"},
 de:{"Practice English your way":"Englisch auf deine Art üben","Today's plan":"Heutiger Plan","Review vocabulary":"Wortschatz wiederholen","Start today's plan":"Heutigen Plan starten","Total progress":"Gesamtfortschritt","Not checked in today":"Heute noch nicht eingecheckt","Start practicing":"Übung starten","Daily check-in":"Täglicher Check-in","Open":"Öffnen","My account":"Mein Konto","Choose what you want to manage":"Wähle, was du verwalten möchtest","Profile":"Profil","Plan and billing":"Tarif und Abrechnung","Settings":"Einstellungen","Data and privacy":"Daten und Datenschutz","Language":"Sprache","Choose the interface language":"Sprache der Benutzeroberfläche wählen","Display language":"Anzeigesprache","Currency is selected automatically: Thai uses THB and other languages use USD":"Die Währung wird automatisch gewählt: Thai nutzt THB, alle anderen Sprachen USD","Theme":"Design","Light":"Hell","Dark":"Dunkel","Sound":"Ton","Choose the plan that fits you":"Wähle den passenden Tarif","Keep learning at an accessible price":"Weiterlernen zu einem fairen Preis","Starter":"Einstieg","Current plan":"Aktueller Tarif","Best value":"Bestes Angebot","Yearly":"Jährlich","Flexible":"Flexibel","Manage membership":"Mitgliedschaft verwalten","Important questions":"Wichtige Fragen","Create new set":"Neues Set","Import CSV":"CSV importieren","Edit":"Bearbeiten","Delete":"Löschen","Private":"Privat","Public":"Öffentlich","Submit answers":"Antworten absenden","Time remaining":"Verbleibende Zeit","Correct":"Richtig","Incorrect":"Falsch","Cancel":"Abbrechen","Save":"Speichern","Search":"Suchen","Popular":"Beliebt","Newest":"Neueste"},
 ru:{"Practice English your way":"Практикуйте английский по-своему","Today's plan":"План на сегодня","Review vocabulary":"Повторить слова","Start today's plan":"Начать план на сегодня","Total progress":"Общий прогресс","Not checked in today":"Сегодня отметки ещё нет","Start practicing":"Начать практику","Daily check-in":"Ежедневная отметка","Open":"Открыть","My account":"Мой аккаунт","Choose what you want to manage":"Выберите раздел управления","Profile":"Профиль","Plan and billing":"Тариф и оплата","Settings":"Настройки","Data and privacy":"Данные и конфиденциальность","Language":"Язык","Choose the interface language":"Выберите язык интерфейса","Display language":"Язык интерфейса","Currency is selected automatically: Thai uses THB and other languages use USD":"Валюта выбирается автоматически: для тайского THB, для остальных языков USD","Theme":"Тема","Light":"Светлая","Dark":"Тёмная","Sound":"Звук","Choose the plan that fits you":"Выберите подходящий тариф","Keep learning at an accessible price":"Продолжайте учиться по доступной цене","Starter":"Начальный","Current plan":"Текущий тариф","Best value":"Выгоднее всего","Yearly":"Годовой","Flexible":"Гибкий","Manage membership":"Управление подпиской","Important questions":"Важные вопросы","Create new set":"Создать набор","Import CSV":"Импорт CSV","Edit":"Изменить","Delete":"Удалить","Private":"Личное","Public":"Общедоступное","Submit answers":"Отправить ответы","Time remaining":"Осталось времени","Correct":"Верно","Incorrect":"Неверно","Cancel":"Отмена","Save":"Сохранить","Search":"Поиск","Popular":"Популярное","Newest":"Новое"},
 hi:{"Practice English your way":"अपने तरीके से अंग्रेज़ी का अभ्यास करें","Today's plan":"आज की योजना","Review vocabulary":"शब्दावली दोहराएँ","Start today's plan":"आज की योजना शुरू करें","Total progress":"कुल प्रगति","Not checked in today":"आज चेक-इन नहीं किया","Start practicing":"अभ्यास शुरू करें","Daily check-in":"दैनिक चेक-इन","Open":"खोलें","My account":"मेरा खाता","Choose what you want to manage":"जिसे प्रबंधित करना है उसे चुनें","Profile":"प्रोफ़ाइल","Plan and billing":"प्लान और बिलिंग","Settings":"सेटिंग्स","Data and privacy":"डेटा और गोपनीयता","Language":"भाषा","Choose the interface language":"इंटरफ़ेस भाषा चुनें","Display language":"प्रदर्शन भाषा","Currency is selected automatically: Thai uses THB and other languages use USD":"मुद्रा अपने आप चुनी जाती है: थाई के लिए THB और अन्य भाषाओं के लिए USD","Theme":"थीम","Light":"हल्का","Dark":"गहरा","Sound":"ध्वनि","Choose the plan that fits you":"अपने लिए सही प्लान चुनें","Keep learning at an accessible price":"किफ़ायती मूल्य पर सीखते रहें","Starter":"शुरुआती","Current plan":"वर्तमान प्लान","Best value":"सबसे किफ़ायती","Yearly":"वार्षिक","Flexible":"लचीला","Manage membership":"सदस्यता प्रबंधित करें","Important questions":"महत्वपूर्ण प्रश्न","Create new set":"नया सेट बनाएँ","Import CSV":"CSV आयात करें","Edit":"संपादित करें","Delete":"हटाएँ","Private":"निजी","Public":"सार्वजनिक","Submit answers":"उत्तर जमा करें","Time remaining":"शेष समय","Correct":"सही","Incorrect":"गलत","Cancel":"रद्द करें","Save":"सहेजें","Search":"खोजें","Popular":"लोकप्रिय","Newest":"नवीनतम"}
};

Object.assign(EN,{
 "แตะเพื่อดูคำแปล":"Tap to reveal the translation","ปัดเพื่อไปคำถัดไป":"Swipe for the next word","Flashcard · ตัวอย่างจริง":"Flashcard · live sample","สำคัญ · มีนัยสำคัญ":"important · significant","ยังไม่จำ":"Still learning","จำได้":"Know it","เข้ากลุ่ม LINE":"Join the LINE group","ทักษะหลัก":"core skills","ข้อใน Mock":"questions in a Mock","นาทีต่อวัน":"minutes a day","ฟรี":"Free","เริ่มเรียนได้ทันที":"Start learning now","ฝึกให้ตรงจุด":"Focused practice","หนึ่งที่สำหรับการเตรียมอังกฤษ A-Level":"One place for A-Level English preparation","ไม่ต้องเปิดหลายแอป และไม่ต้องสร้างชุดเองก่อนเริ่มเรียน":"No need to switch between apps or create a set before you start.","จำศัพท์ด้วย Loop":"Memorize vocabulary with Loop","คำที่ยังไม่จำจะวนกลับมา และบันทึกไว้ทบทวนได้เสมอ":"Words you are still learning return automatically and remain available for review.","Reading พร้อมเครื่องมือ":"Reading with built-in tools","ไฮไลต์ แตะคำ แปล และเก็บคำที่ไม่รู้เข้า Flashcard":"Highlight, tap, translate, and save unfamiliar words to Flashcards.","Listening ตามรูปแบบข้อสอบ":"Exam-style Listening","ฟังบทสนทนา ซ่อน Transcript และตอบคำถามตามบริบท":"Listen to conversations, hide the transcript, and answer in context.","Mock Exam คู่ขนาน":"Original parallel Mock Exams","ซ้อมเวลา ตรวจคะแนน และดูคำอธิบายหลังส่งคำตอบ":"Practice under time limits, check scores, and review explanations after submitting.","เริ่มง่าย":"Easy to start","รู้ว่าต้องทำอะไรต่อในทุกวัน":"Know what to do next every day","เลือกเป้าหมาย":"Choose a goal","กำหนดทักษะและเวลาที่ต้องการฝึก":"Choose the skills and time you want to practice.","ฝึกตามแผน":"Follow your plan","เริ่มจากชุดพร้อมเรียนและจุดอ่อนของคุณ":"Start with ready-to-learn sets and your weak points.","วัดพัฒนาการ":"Track progress","ดูคะแนน คำที่จำได้ และกลับมาทบทวน":"See scores, mastered words, and return to review.","เริ่มต้นโดยไม่ต้องจ่าย":"Start without paying","Free ใช้งานได้จริง":"A genuinely useful Free plan","Pro เมื่ออยากฝึกได้มากขึ้น":"Pro when you want more practice","ดูแพ็กเกจทั้งหมด":"See all plans","ฝึกอังกฤษให้เป็นระบบในแบบของคุณ":"Build a consistent English practice routine your way","ต่อเดือน":"per month","หรือรายปีเฉลี่ย":"or yearly, equivalent to"
});
Object.assign(ZH,{
 "สำคัญ · มีนัยสำคัญ":"重要 · 显著",
 "ฝึกอังกฤษครบทั้ง":"完整练习英语","ศัพท์ ทักษะ และข้อสอบ":"词汇、技能与考试","วางแผนฝึกจากจุดอ่อนของคุณ ทบทวนศัพท์ด้วย Loop และลองข้อสอบคู่ขนานที่สร้างใหม่โดยไม่คัดลอกข้อสอบจริง":"针对薄弱点制定练习计划，用 Loop 复习词汇，并尝试原创的平行模拟题。","ไม่ต้องใช้บัตร":"无需银行卡","มีแพ็กเกจฟรี":"提供免费方案","ใช้ได้บนมือถือ":"支持手机使用","แตะเพื่อดูคำแปล":"点击查看翻译","ยังไม่จำ":"还在学习","จำได้":"已掌握","ทักษะหลัก":"核心技能","ข้อใน Mock":"完整模拟题数量","นาทีต่อวัน":"每天分钟","ฟรี":"免费","เริ่มเรียนได้ทันที":"立即开始学习","ฝึกให้ตรงจุด":"针对性练习","หนึ่งที่สำหรับการเตรียมอังกฤษ A-Level":"一站式准备 A-Level 英语","ไม่ต้องเปิดหลายแอป และไม่ต้องสร้างชุดเองก่อนเริ่มเรียน":"无需切换多个应用，也无需先创建内容。","จำศัพท์ด้วย Loop":"用 Loop 记忆词汇","คำที่ยังไม่จำจะวนกลับมา และบันทึกไว้ทบทวนได้เสมอ":"尚未掌握的单词会自动回来，并可随时复习。","Reading พร้อมเครื่องมือ":"带工具的阅读练习","ไฮไลต์ แตะคำ แปล และเก็บคำที่ไม่รู้เข้า Flashcard":"高亮、点击、翻译，并把生词保存到单词卡。","Listening ตามรูปแบบข้อสอบ":"考试形式的听力练习","ฟังบทสนทนา ซ่อน Transcript และตอบคำถามตามบริบท":"听对话、隐藏文字稿，并根据语境回答。","Mock Exam คู่ขนาน":"原创平行模拟考试","ซ้อมเวลา ตรวจคะแนน และดูคำอธิบายหลังส่งคำตอบ":"限时练习、查看分数，并在提交后阅读解析。","เริ่มง่าย":"轻松开始","รู้ว่าต้องทำอะไรต่อในทุกวัน":"每天都知道下一步该做什么","เลือกเป้าหมาย":"选择目标","กำหนดทักษะและเวลาที่ต้องการฝึก":"选择想练习的技能和时间。","ฝึกตามแผน":"按计划练习","เริ่มจากชุดพร้อมเรียนและจุดอ่อนของคุณ":"从现成内容和你的薄弱点开始。","วัดพัฒนาการ":"跟踪进步","ดูคะแนน คำที่จำได้ และกลับมาทบทวน":"查看分数和已掌握单词，并随时复习。","เริ่มต้นโดยไม่ต้องจ่าย":"免费开始","Free ใช้งานได้จริง":"真正实用的免费方案","Pro เมื่ออยากฝึกได้มากขึ้น":"需要更多练习时升级 Pro","ดูแพ็กเกจทั้งหมด":"查看全部套餐","ฝึกอังกฤษให้เป็นระบบในแบบของคุณ":"以自己的方式建立系统的英语练习","ต่อเดือน":"每月","หรือรายปีเฉลี่ย":"或年付平均"
});
const EXTRA_LOCALIZED={
 ja:{"Time":"時間","Moves":"手数","Pairs":"ペア","Check answers":"答えを確認","Clear answers":"解答を消去","Clues":"ヒント","Choose a vocabulary set":"単語セットを選択","Flashcard settings":"単語カード設定","Words per Loop":"1ループの単語数","Auto-play pronunciation":"発音を自動再生","Show translation immediately":"訳をすぐ表示","Shuffle words":"順番をシャッフル","Loop completed":"ループ完了","Back to sets":"セット一覧へ","Create vocabulary set":"単語セットを作成","Edit vocabulary set":"単語セットを編集","Set name":"セット名","Visibility":"公開範囲","Add word":"単語を追加","Meaning":"意味","Example sentence":"例文","Duplicate":"複製","Save set":"セットを保存","Bulk import":"一括インポート","Choose file":"ファイルを選択","Match columns":"列を対応付け","Review data":"データを確認","Confirm import":"インポートを確定","Create practice set":"練習セットを作成","Edit practice set":"練習セットを編集","Questions":"問題","Confirm deletion":"削除の確認","Deletion cannot be undone":"削除は取り消せません","Confirm":"確認","Rate this practice set":"練習セットを評価","Review":"レビュー","Report content":"コンテンツを報告","Reason":"理由","Details":"詳細","Submit report":"報告を送信","Sign in with Google":"Googleでログイン"},
 ko:{"Time":"시간","Moves":"횟수","Pairs":"쌍","Check answers":"정답 확인","Clear answers":"답안 지우기","Clues":"힌트","Choose a vocabulary set":"어휘 세트 선택","Flashcard settings":"플래시카드 설정","Words per Loop":"루프당 단어 수","Auto-play pronunciation":"발음 자동 재생","Show translation immediately":"번역 바로 표시","Shuffle words":"단어 순서 섞기","Loop completed":"루프 완료","Back to sets":"세트로 돌아가기","Create vocabulary set":"어휘 세트 만들기","Edit vocabulary set":"어휘 세트 수정","Set name":"세트 이름","Visibility":"공개 범위","Add word":"단어 추가","Meaning":"뜻","Example sentence":"예문","Duplicate":"복제","Save set":"세트 저장","Bulk import":"대량 가져오기","Choose file":"파일 선택","Match columns":"열 연결","Review data":"데이터 확인","Confirm import":"가져오기 확인","Create practice set":"연습 세트 만들기","Edit practice set":"연습 세트 수정","Questions":"문제","Confirm deletion":"삭제 확인","Deletion cannot be undone":"삭제하면 되돌릴 수 없습니다","Confirm":"확인","Rate this practice set":"연습 세트 평가","Review":"리뷰","Report content":"콘텐츠 신고","Reason":"이유","Details":"상세 내용","Submit report":"신고 제출","Sign in with Google":"Google로 로그인"},
 pt:{"Time":"Tempo","Moves":"Jogadas","Pairs":"Pares","Check answers":"Verificar respostas","Clear answers":"Limpar respostas","Clues":"Dicas","Choose a vocabulary set":"Escolha um conjunto de vocabulário","Flashcard settings":"Configurações dos flashcards","Words per Loop":"Palavras por ciclo","Auto-play pronunciation":"Reproduzir pronúncia automaticamente","Show translation immediately":"Mostrar tradução imediatamente","Shuffle words":"Embaralhar palavras","Loop completed":"Ciclo concluído","Back to sets":"Voltar aos conjuntos","Create vocabulary set":"Criar conjunto de vocabulário","Edit vocabulary set":"Editar conjunto de vocabulário","Set name":"Nome do conjunto","Visibility":"Visibilidade","Add word":"Adicionar palavra","Meaning":"Significado","Example sentence":"Frase de exemplo","Duplicate":"Duplicar","Save set":"Salvar conjunto","Bulk import":"Importação em massa","Choose file":"Escolher arquivo","Match columns":"Associar colunas","Review data":"Revisar dados","Confirm import":"Confirmar importação","Create practice set":"Criar conjunto de prática","Edit practice set":"Editar conjunto de prática","Questions":"Perguntas","Confirm deletion":"Confirmar exclusão","Deletion cannot be undone":"A exclusão não pode ser desfeita","Confirm":"Confirmar","Rate this practice set":"Avaliar conjunto de prática","Review":"Avaliação","Report content":"Denunciar conteúdo","Reason":"Motivo","Details":"Detalhes","Submit report":"Enviar denúncia","Sign in with Google":"Entrar com Google"},
 de:{"Time":"Zeit","Moves":"Züge","Pairs":"Paare","Check answers":"Antworten prüfen","Clear answers":"Antworten löschen","Clues":"Hinweise","Choose a vocabulary set":"Wortschatzset auswählen","Flashcard settings":"Karteikarten-Einstellungen","Words per Loop":"Wörter pro Runde","Auto-play pronunciation":"Aussprache automatisch abspielen","Show translation immediately":"Übersetzung sofort anzeigen","Shuffle words":"Wörter mischen","Loop completed":"Runde abgeschlossen","Back to sets":"Zurück zu den Sets","Create vocabulary set":"Wortschatzset erstellen","Edit vocabulary set":"Wortschatzset bearbeiten","Set name":"Setname","Visibility":"Sichtbarkeit","Add word":"Wort hinzufügen","Meaning":"Bedeutung","Example sentence":"Beispielsatz","Duplicate":"Duplizieren","Save set":"Set speichern","Bulk import":"Massenimport","Choose file":"Datei auswählen","Match columns":"Spalten zuordnen","Review data":"Daten prüfen","Confirm import":"Import bestätigen","Create practice set":"Übungsset erstellen","Edit practice set":"Übungsset bearbeiten","Questions":"Fragen","Confirm deletion":"Löschen bestätigen","Deletion cannot be undone":"Das Löschen kann nicht rückgängig gemacht werden","Confirm":"Bestätigen","Rate this practice set":"Übungsset bewerten","Review":"Bewertung","Report content":"Inhalt melden","Reason":"Grund","Details":"Details","Submit report":"Meldung senden","Sign in with Google":"Mit Google anmelden"},
 ru:{"Time":"Время","Moves":"Ходы","Pairs":"Пары","Check answers":"Проверить ответы","Clear answers":"Очистить ответы","Clues":"Подсказки","Choose a vocabulary set":"Выберите набор слов","Flashcard settings":"Настройки карточек","Words per Loop":"Слов в цикле","Auto-play pronunciation":"Автоматически произносить","Show translation immediately":"Сразу показывать перевод","Shuffle words":"Перемешать слова","Loop completed":"Цикл завершён","Back to sets":"Назад к наборам","Create vocabulary set":"Создать набор слов","Edit vocabulary set":"Изменить набор слов","Set name":"Название набора","Visibility":"Видимость","Add word":"Добавить слово","Meaning":"Значение","Example sentence":"Пример предложения","Duplicate":"Создать копию","Save set":"Сохранить набор","Bulk import":"Массовый импорт","Choose file":"Выбрать файл","Match columns":"Сопоставить столбцы","Review data":"Проверить данные","Confirm import":"Подтвердить импорт","Create practice set":"Создать набор упражнений","Edit practice set":"Изменить набор упражнений","Questions":"Вопросы","Confirm deletion":"Подтвердить удаление","Deletion cannot be undone":"Удаление нельзя отменить","Confirm":"Подтвердить","Rate this practice set":"Оценить набор упражнений","Review":"Отзыв","Report content":"Пожаловаться на материал","Reason":"Причина","Details":"Подробности","Submit report":"Отправить жалобу","Sign in with Google":"Войти через Google"},
 hi:{"Time":"समय","Moves":"चालें","Pairs":"जोड़े","Check answers":"उत्तर जाँचें","Clear answers":"उत्तर साफ़ करें","Clues":"संकेत","Choose a vocabulary set":"शब्दावली सेट चुनें","Flashcard settings":"फ़्लैशकार्ड सेटिंग्स","Words per Loop":"प्रति लूप शब्द","Auto-play pronunciation":"उच्चारण अपने आप चलाएँ","Show translation immediately":"अनुवाद तुरंत दिखाएँ","Shuffle words":"शब्दों का क्रम बदलें","Loop completed":"लूप पूरा हुआ","Back to sets":"सेट पर वापस जाएँ","Create vocabulary set":"शब्दावली सेट बनाएँ","Edit vocabulary set":"शब्दावली सेट संपादित करें","Set name":"सेट का नाम","Visibility":"दृश्यता","Add word":"शब्द जोड़ें","Meaning":"अर्थ","Example sentence":"उदाहरण वाक्य","Duplicate":"प्रतिलिपि बनाएँ","Save set":"सेट सहेजें","Bulk import":"एक साथ आयात","Choose file":"फ़ाइल चुनें","Match columns":"कॉलम मिलाएँ","Review data":"डेटा जाँचें","Confirm import":"आयात की पुष्टि करें","Create practice set":"अभ्यास सेट बनाएँ","Edit practice set":"अभ्यास सेट संपादित करें","Questions":"प्रश्न","Confirm deletion":"हटाने की पुष्टि करें","Deletion cannot be undone":"हटाने के बाद वापस नहीं किया जा सकता","Confirm":"पुष्टि करें","Rate this practice set":"अभ्यास सेट को रेट करें","Review":"समीक्षा","Report content":"सामग्री की रिपोर्ट करें","Reason":"कारण","Details":"विवरण","Submit report":"रिपोर्ट भेजें","Sign in with Google":"Google से साइन इन करें"}
};
for(const [lang,entries] of Object.entries(EXTRA_LOCALIZED))Object.assign(LOCALIZED[lang],entries);

Object.assign(EN,{"นำเข้าหลายคำ":"Bulk import","ชุดทางการ":"Official set","ออกบ่อย":"Frequent","ควรรู้":"Essential","คู่ขนาน":"Parallel","แนวนอน":"Across","แนวตั้ง":"Down","เติมคำแนวนอนและแนวตั้งที่ตัดกันจากคำใบ้":"Fill intersecting across and down words from the clues"});
Object.assign(ZH,{"นำเข้าหลายคำ":"批量导入","ชุดทางการ":"官方内容","ออกบ่อย":"高频","ควรรู้":"必备","คู่ขนาน":"同等难度","แนวนอน":"横向","แนวตั้ง":"纵向","เติมคำแนวนอนและแนวตั้งที่ตัดกันจากคำใบ้":"根据提示填写相交的横向和纵向单词"});
const COMMON_LOCALIZED={
 ja:{"Bulk import":"一括インポート","Official set":"公式セット","Frequent":"頻出","Essential":"必須","Parallel":"同等レベル","Across":"横","Down":"縦","Start Flashcards":"フラッシュカードを開始","Start Match":"マッチを開始","Start Crossword":"クロスワードを開始","words":"語","Created by":"作成者"},
 ko:{"Bulk import":"일괄 가져오기","Official set":"공식 세트","Frequent":"빈출","Essential":"필수","Parallel":"동등 난이도","Across":"가로","Down":"세로","Start Flashcards":"플래시카드 시작","Start Match":"매치 시작","Start Crossword":"십자말풀이 시작","words":"단어","Created by":"제작자"},
 pt:{"Bulk import":"Importação em massa","Official set":"Conjunto oficial","Frequent":"Frequentes","Essential":"Essenciais","Parallel":"Nível equivalente","Across":"Horizontal","Down":"Vertical","Start Flashcards":"Iniciar flashcards","Start Match":"Iniciar combinação","Start Crossword":"Iniciar palavras cruzadas","words":"palavras","Created by":"Criado por"},
 de:{"Bulk import":"Massenimport","Official set":"Offizielles Set","Frequent":"Häufig","Essential":"Grundwortschatz","Parallel":"Gleiches Niveau","Across":"Waagerecht","Down":"Senkrecht","Start Flashcards":"Karteikarten starten","Start Match":"Zuordnung starten","Start Crossword":"Kreuzworträtsel starten","words":"Wörter","Created by":"Erstellt von"},
 ru:{"Bulk import":"Массовый импорт","Official set":"Официальный набор","Frequent":"Частые","Essential":"Основные","Parallel":"Эквивалентный уровень","Across":"По горизонтали","Down":"По вертикали","Start Flashcards":"Начать карточки","Start Match":"Начать сопоставление","Start Crossword":"Начать кроссворд","words":"слов","Created by":"Автор"},
 hi:{"Bulk import":"एक साथ आयात","Official set":"आधिकारिक सेट","Frequent":"बार-बार आने वाले","Essential":"आवश्यक","Parallel":"समान स्तर","Across":"आड़ा","Down":"खड़ा","Start Flashcards":"फ़्लैशकार्ड शुरू करें","Start Match":"मैच शुरू करें","Start Crossword":"क्रॉसवर्ड शुरू करें","words":"शब्द","Created by":"निर्माता"}
};
for(const [lang,entries] of Object.entries(COMMON_LOCALIZED))Object.assign(LOCALIZED[lang],entries);

Object.assign(EN,{
 "เวลา":"Time","ครั้ง":"Moves","คู่":"Pairs","เติมคำจากคำใบ้โดยใช้เฉพาะคำที่จำแล้ว":"Fill the grid from clues using mastered words","จับคู่คำศัพท์กับความหมายให้ครบโดยใช้จำนวนครั้งให้น้อยที่สุด":"Match every word to its meaning in as few moves as possible","ตรวจคำตอบ":"Check answers","ล้างคำตอบ":"Clear answers","คำใบ้":"Clues","ตัวอักษร":"letters","คำที่":"Word","จบ Match ใน":"Finished Match in","วินาที":"seconds","ถูกทั้งหมด · ใช้เวลา":"All correct · Time",
 "เลือกชุดคำศัพท์":"Choose a vocabulary set","เลือกชุดก่อนเริ่มฝึก แก้ไข ลบ และกำหนดการมองเห็นได้":"Choose a set to practice, edit, delete, or change visibility","ตั้งค่า Flashcard":"Flashcard settings","จำนวนคำใน Loop":"Words per Loop","กำหนดจำนวนคำที่จะวนซ้ำในรอบนี้":"Set how many words repeat in this round","อ่านเสียงอัตโนมัติ":"Auto-play pronunciation","แสดงคำแปลทันที":"Show translation immediately","สุ่มลำดับคำ":"Shuffle words","จำครบ Loop นี้แล้ว":"Loop completed","กำหนด Loop ถัดไป":"Set the next Loop","กลับหน้าเลือกชุด":"Back to sets","สร้างชุดคำศัพท์":"Create vocabulary set","แก้ไขชุดคำศัพท์":"Edit vocabulary set","ชื่อชุด":"Set name","การมองเห็น":"Visibility","เพิ่มคำศัพท์":"Add word","คำหรือวลี":"Word or phrase","ความหมาย":"Meaning","ประโยคตัวอย่าง":"Example sentence","ทำสำเนา":"Duplicate","บันทึกชุด":"Save set",
 "นำเข้าข้อมูลจำนวนมาก":"Bulk import","เลือกไฟล์":"Choose file","จับคู่คอลัมน์":"Match columns","ตรวจข้อมูล":"Review data","ยืนยันนำเข้า":"Confirm import","ดาวน์โหลดเทมเพลต CSV":"Download CSV template","เลือกไฟล์ CSV":"Choose CSV file","ระบบจะแสดงตัวอย่างและยังไม่บันทึกทันที":"A preview will be shown before anything is saved","ข้อมูลทั้งหมดพร้อมนำเข้า":"All data is ready to import","รายการที่มีปัญหาจะไม่ถูกนำเข้า":"Rows with errors will not be imported","พร้อมนำเข้า":"Ready to import","ต้องแก้":"Needs fixing","สถานะ":"Status","ไปขั้นยืนยัน":"Continue to confirmation","นำเข้าเป็นฉบับร่างส่วนตัวเรียบร้อยแล้ว":"Imported successfully as a private draft",
 "สร้างชุดฝึก":"Create practice set","แก้ไขชุดฝึก":"Edit practice set","เวลา (นาที)":"Time (minutes)","ประเภท":"Type","หมวด/ประเภท":"Category / type","บทความ":"Passage","บทสนทนา / Transcript":"Conversation / transcript","ข้อความหรือ Passage":"Text or passage","ใส่เนื้อหาที่ผู้เรียนจะใช้ตอบคำถาม":"Enter the content learners will use to answer","คำถาม":"Questions","Sections และข้อสอบ":"Sections and questions","ยืนยันการลบ":"Confirm deletion","การลบไม่สามารถย้อนกลับได้":"Deletion cannot be undone","พิมพ์คำว่า ลบ":"Type Delete","ฉันเข้าใจว่ารายการนี้จะถูกลบถาวร":"I understand this item will be permanently deleted","ยืนยัน":"Confirm","ยืนยันเผยแพร่":"Confirm publication","โควตาชุดส่วนตัวเต็ม":"Private-set limit reached",
 "ให้คะแนนชุดฝึก":"Rate this practice set","รีวิว":"Review","บอกสิ่งที่เป็นประโยชน์กับผู้เรียนคนอื่น":"Share something useful for other learners","รายงานเนื้อหา":"Report content","เหตุผล":"Reason","รายละเอียด":"Details","ข้อมูลหรือเฉลยไม่ถูกต้อง":"Incorrect information or answer key","ละเมิดลิขสิทธิ์":"Copyright infringement","Spam หรือโฆษณา":"Spam or advertising","เนื้อหาไม่เหมาะสม":"Inappropriate content","อธิบายสิ่งที่พบ":"Describe the issue","ส่งรายงาน":"Submit report","เข้าสู่ระบบ Google":"Sign in with Google","สมัครฟรีด้วย Google":"Continue free with Google"
});
Object.assign(ZH,{
 "เวลา":"时间","ครั้ง":"步数","คู่":"配对","เติมคำจากคำใบ้โดยใช้เฉพาะคำที่จำแล้ว":"根据提示，用已掌握的单词完成填字游戏","จับคู่คำศัพท์กับความหมายให้ครบโดยใช้จำนวนครั้งให้น้อยที่สุด":"用尽可能少的步数完成单词与释义配对","ตรวจคำตอบ":"检查答案","ล้างคำตอบ":"清除答案","คำใบ้":"提示","ตัวอักษร":"个字母","คำที่":"单词","วินาที":"秒","ถูกทั้งหมด · ใช้เวลา":"全部正确 · 用时",
 "เลือกชุดคำศัพท์":"选择词汇集","เลือกชุดก่อนเริ่มฝึก แก้ไข ลบ และกำหนดการมองเห็นได้":"选择要练习的词汇集，也可编辑、删除或设置可见性","ตั้งค่า Flashcard":"单词卡设置","จำนวนคำใน Loop":"每轮单词数","กำหนดจำนวนคำที่จะวนซ้ำในรอบนี้":"设置本轮循环复习的单词数量","อ่านเสียงอัตโนมัติ":"自动朗读","แสดงคำแปลทันที":"立即显示翻译","สุ่มลำดับคำ":"随机排序","จำครบ Loop นี้แล้ว":"本轮已完成","กำหนด Loop ถัดไป":"设置下一轮","กลับหน้าเลือกชุด":"返回词汇集","สร้างชุดคำศัพท์":"创建词汇集","แก้ไขชุดคำศัพท์":"编辑词汇集","ชื่อชุด":"名称","การมองเห็น":"可见性","เพิ่มคำศัพท์":"添加单词","คำหรือวลี":"单词或短语","ความหมาย":"释义","ประโยคตัวอย่าง":"例句","ทำสำเนา":"复制","บันทึกชุด":"保存词汇集",
 "นำเข้าข้อมูลจำนวนมาก":"批量导入","เลือกไฟล์":"选择文件","จับคู่คอลัมน์":"匹配列","ตรวจข้อมูล":"检查数据","ยืนยันนำเข้า":"确认导入","ดาวน์โหลดเทมเพลต CSV":"下载 CSV 模板","เลือกไฟล์ CSV":"选择 CSV 文件","ระบบจะแสดงตัวอย่างและยังไม่บันทึกทันที":"系统会先显示预览，不会立即保存","ข้อมูลทั้งหมดพร้อมนำเข้า":"所有数据均可导入","รายการที่มีปัญหาจะไม่ถูกนำเข้า":"有问题的行不会被导入","พร้อมนำเข้า":"可导入","ต้องแก้":"需要修正","สถานะ":"状态","ไปขั้นยืนยัน":"继续确认","นำเข้าเป็นฉบับร่างส่วนตัวเรียบร้อยแล้ว":"已成功导入为私人草稿",
 "สร้างชุดฝึก":"创建练习集","แก้ไขชุดฝึก":"编辑练习集","เวลา (นาที)":"时间（分钟）","ประเภท":"类型","หมวด/ประเภท":"类别 / 类型","บทความ":"文章","บทสนทนา / Transcript":"对话 / 文字稿","ข้อความหรือ Passage":"文本或文章","ใส่เนื้อหาที่ผู้เรียนจะใช้ตอบคำถาม":"输入学习者答题所需的内容","คำถาม":"问题","Sections และข้อสอบ":"章节与题目","ยืนยันการลบ":"确认删除","การลบไม่สามารถย้อนกลับได้":"删除后无法恢复","พิมพ์คำว่า ลบ":"输入“删除”","ฉันเข้าใจว่ารายการนี้จะถูกลบถาวร":"我了解此项目将被永久删除","ยืนยัน":"确认","ยืนยันเผยแพร่":"确认发布","โควตาชุดส่วนตัวเต็ม":"私人内容数量已达上限",
 "ให้คะแนนชุดฝึก":"评价练习集","รีวิว":"评价","บอกสิ่งที่เป็นประโยชน์กับผู้เรียนคนอื่น":"分享对其他学习者有帮助的内容","รายงานเนื้อหา":"举报内容","เหตุผล":"原因","รายละเอียด":"详情","ข้อมูลหรือเฉลยไม่ถูกต้อง":"信息或答案有误","ละเมิดลิขสิทธิ์":"侵犯版权","Spam หรือโฆษณา":"垃圾信息或广告","เนื้อหาไม่เหมาะสม":"内容不当","อธิบายสิ่งที่พบ":"描述发现的问题","ส่งรายงาน":"提交举报","เข้าสู่ระบบ Google":"使用 Google 登录","สมัครฟรีด้วย Google":"使用 Google 免费开始"
});
Object.assign(EN,{
 "หน้าฝึกคงรูปแบบจริงจังแบบข้อสอบ แต่ใช้เนื้อหาที่สร้างใหม่สำหรับ Jumsup":"The practice interface follows an exam format using original content created for Jumsup.","+ สร้างชุดใหม่":"+ Create new set","ค้นหาใน Community":"Search Community","ค้นหา เปรียบเทียบ และนำเข้าชุดฝึกจากผู้สร้างคนอื่น":"Search, compare, and import sets from other creators","การนำเข้า":"Imports","คะแนนเฉลี่ย":"Average rating","ชุดคำศัพท์":"Vocabulary sets","ชุดฝึกทักษะ":"Practice sets","ค้นหาชื่อชุด หรือ username ผู้สร้าง...":"Search by set name or creator username...","รีเฟรช":"Refresh","คุณดูชุดและสถิติได้โดยไม่ต้อง Login แต่ต้องเข้าสู่ระบบก่อนนำเข้าหรือให้คะแนนบนระบบออนไลน์":"You can browse sets and statistics without signing in. Sign in to import or rate online content.","เข้าสู่ระบบ Google":"Sign in with Google","รายการ":"items","ถูกใจ":"likes","นำเข้า":"Import","ถูกใจแล้ว":"Liked","ให้คะแนน":"Rate","รายงาน":"Report","โหมดอ่านแบบข้อสอบ + Readlang: แตะคำอังกฤษเพื่อดูคำแปลและเพิ่มเข้า Flashcard":"Exam-style reading with Readlang: tap an English word to translate it and save it to Flashcards","แตะคำศัพท์ในบทความ":"Tap a word in the passage","ดูคำแปลทันที":"See its translation instantly","เพิ่มเข้า Flashcard":"Add it to Flashcards","ทบทวนในชุดคำศัพท์":"Review it in a vocabulary set","ทักษะที่วัด":"Skills assessed","Short / Long Conversation พร้อม TTS สำเนียงและความเร็วเสียง":"Short and long conversations with adjustable TTS accent and speed","Practice mode · ฟังซ้ำได้":"Practice mode · Replay allowed","ฟังรอบแรกเพื่อจับสถานการณ์และเจตนา จากนั้นจึงฟังรายละเอียดในรอบถัดไป":"Listen once for the situation and intention, then replay for details.","ตรวจ tense, word form, connector, reference และลำดับเหตุผลของทั้งย่อหน้า":"Check tense, word form, connectors, references, and paragraph logic.","แบบจำลองโครงสร้าง 80 ข้อ 90 นาที พร้อมกระดาษคำตอบ":"An 80-question, 90-minute simulation with an answer sheet","โจทย์ทั้งหมดเป็นเนื้อหาที่ Jumsup เขียนขึ้นใหม่ ไม่ใช่ข้อสอบจริง":"All questions are original Jumsup content, not official exam questions.","ตรวจคำตอบและอ่านคำอธิบายก่อนเริ่มรอบใหม่":"Review answers and explanations before starting another attempt","ตอบถูก":"Correct answers","จาก":"out of","ใช้เวลา":"Time used","คำตอบของคุณ":"Your answer","ตรวจจากใจความ ไวยากรณ์ และบริบทของคำถาม":"Review the meaning, grammar, and context of the question"
});
Object.assign(ZH,{
 "หน้าฝึกคงรูปแบบจริงจังแบบข้อสอบ แต่ใช้เนื้อหาที่สร้างใหม่สำหรับ Jumsup":"练习界面采用正式考试形式，内容均为 Jumsup 原创。","+ สร้างชุดใหม่":"+ 新建练习","ค้นหาใน Community":"在社区中搜索","ค้นหา เปรียบเทียบ และนำเข้าชุดฝึกจากผู้สร้างคนอื่น":"搜索、比较并导入其他创作者的练习内容","การนำเข้า":"导入次数","คะแนนเฉลี่ย":"平均评分","ชุดคำศัพท์":"词汇集","ชุดฝึกทักษะ":"技能练习","ค้นหาชื่อชุด หรือ username ผู้สร้าง...":"按内容名称或创作者用户名搜索…","รีเฟรช":"刷新","นำเข้า":"导入","ถูกใจแล้ว":"已喜欢","ถูกใจ":"喜欢","ให้คะแนน":"评分","รายงาน":"举报","รายการ":"项","ทักษะที่วัด":"考查技能","Practice mode · ฟังซ้ำได้":"练习模式 · 可重复播放","โจทย์ทั้งหมดเป็นเนื้อหาที่ Jumsup เขียนขึ้นใหม่ ไม่ใช่ข้อสอบจริง":"所有题目均由 Jumsup 原创，并非官方试题。","ตรวจคำตอบและอ่านคำอธิบายก่อนเริ่มรอบใหม่":"开始新一轮前查看答案与解析","คำตอบของคุณ":"你的答案"
});

const phraseCache=new WeakMap();
function replaceKnown(text,map){
 let entries=phraseCache.get(map);
 if(!entries){entries=Object.entries(map).filter(([from])=>from.length>=4).sort((a,b)=>b[0].length-a[0].length);phraseCache.set(map,entries)}
 for(const [from,to] of entries)if(text.includes(from))text=text.replaceAll(from,to);
 return text;
}
/** Translate a single UI string (used for document.title etc). Returns the
 *  input unchanged for Thai or when no translation is known. */
export function translatePhrase(lang,value){
 if(lang==="th"||typeof value!=="string"||!value.trim())return value;
 const primary=lang==="zh"?ZH:EN,secondary=LOCALIZED[lang]||{};
 const leading=value.match(/^\s*/)?.[0]||"",trailing=value.match(/\s*$/)?.[0]||"",key=value.trim();
 let first=primary[key];
 if(!first&&key.startsWith("✓ "))first=`✓ ${primary[key.slice(2)]||key.slice(2)}`;
 if(!first&&key.startsWith("Pro เริ่ม "))first=key.replace("Pro เริ่ม ",lang==="zh"?"Pro 起价 ":"Pro starts at ").replaceAll("/เดือน",lang==="zh"?"/月":"/month").replace(" หรือรายปีเฉลี่ย ",lang==="zh"?"，或年付平均 ":", or yearly equivalent to ");
 if(!first){let m;if((m=key.match(/^(\d+) วัน$/)))first=lang==="zh"?`${m[1]} 天`:`${m[1]} days`;else if((m=key.match(/^ใน (\d+) วัน$/)))first=lang==="zh"?`${m[1]} 天后`:`in ${m[1]} days`;else if((m=key.match(/^\((\d+) ตัวอักษร\)$/)))first=lang==="zh"?`(${m[1]} 个字母)`:`(${m[1]} letters)`;else if((m=key.match(/^สมัครเพื่อใช้ (.+)$/)))first=lang==="zh"?`注册后即可使用${primary[m[1]]||m[1]}`:`Sign up to use ${primary[m[1]]||m[1]}`;else if((m=key.match(/^(\d+) ชุด$/)))first=lang==="zh"?`${m[1]} 套`:`${m[1]} sets`;else if((m=key.match(/^(\d+) คำ · สร้างโดย (.+)$/)))first=lang==="zh"?`${m[1]} 个单词 · 创建者 ${m[2]}`:`${m[1]} words · Created by ${m[2]}`;else if((m=key.match(/^เริ่ม (Flashcards|Match|Crossword)$/)))first=lang==="zh"?`开始${m[1]}`:`Start ${m[1]}`;else if((m=key.match(/^(\d+) รายการ · สร้างโดย (.+)$/)))first=lang==="zh"?`${m[1]} 项 · 创建者 ${m[2]}`:`${m[1]} items · Created by ${m[2]}`;else if((m=key.match(/^สร้างโดย (.+) · (\d+) นาที · (\d+) ข้อ$/)))first=lang==="zh"?`创建者 ${m[1]} · ${m[2]} 分钟 · ${m[3]} 题`:`Created by ${m[1]} · ${m[2]} minutes · ${m[3]} questions`;else if(key==="♡ ถูกใจ")first=lang==="zh"?"♡ 喜欢":"♡ Like";else if(key==="♥ ถูกใจแล้ว")first=lang==="zh"?"♥ 已喜欢":"♥ Liked";}
 first=first||replaceKnown(key,primary);const localized=secondary[first]||replaceKnown(first,secondary);return leading+localized+trailing;
}

export function localizePage(root,lang){
 if(lang==="th")return;
 const translate=value=>translatePhrase(lang,value);
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
 // [data-noi18n] marks learner-authored content (vocab meanings, passages) that
 // must never be machine-translated — showing English there defeats the point.
 while((node=walker.nextNode())){if(node.parentElement?.closest("script,style,[data-noi18n]"))continue;node.nodeValue=translate(node.nodeValue)}
 root.querySelectorAll("[placeholder],[aria-label],[title]").forEach(el=>{if(el.closest("[data-noi18n]"))return;for(const attr of ["placeholder","aria-label","title"]){const value=el.getAttribute(attr);if(value)el.setAttribute(attr,translate(value))}});
}

