export const languages=[
 ["th","ไทย"],["en","English"],["zh","中文"],["ja","日本語"],["ko","한국어"],
 ["pt","Português (Brasil)"],["de","Deutsch"],["ru","Русский"],["hi","हिन्दी"]
];
const t={
 th:{home:"Home",vocab:"คำศัพท์",practice:"ฝึกทักษะ",manage:"จัดการ",system:"ระบบ",flash:"Flashcard",match:"Match",cross:"Crossword",reading:"Reading",listening:"Listening",writing:"Writing",mock:"Mock Exam",weak:"จุดอ่อน",community:"Community",add:"เพิ่มเนื้อหา",mine:"เนื้อหาของฉัน",account:"บัญชี",profile:"โปรไฟล์",settings:"ตั้งค่า"},
 en:{home:"Home",vocab:"Vocabulary",practice:"Practice Skills",manage:"Manage",system:"System",flash:"Flashcards",match:"Match",cross:"Crossword",reading:"Reading",listening:"Listening",writing:"Writing",mock:"Mock Exam",weak:"Weak Points",community:"Community",add:"Add Content",mine:"My Content",account:"Account",profile:"Profile",pricing:"Pricing",settings:"Settings"},
 zh:{home:"主页",vocab:"词汇",practice:"技能练习",manage:"管理",system:"系统",flash:"单词卡",match:"配对",cross:"填字游戏",reading:"阅读",listening:"听力",writing:"写作",mock:"模拟考试",weak:"薄弱点",community:"社区",add:"添加内容",mine:"我的内容",account:"账户",profile:"个人资料",pricing:"价格",settings:"设置"},
 ja:{home:"ホーム",vocab:"単語",practice:"スキル練習",manage:"管理",system:"システム",flash:"単語カード",match:"マッチ",cross:"クロスワード",reading:"リーディング",listening:"リスニング",writing:"ライティング",mock:"模擬試験",weak:"弱点",community:"コミュニティ",add:"コンテンツ追加",mine:"マイコンテンツ",account:"アカウント",profile:"プロフィール",pricing:"料金",settings:"設定"},
 ko:{home:"홈",vocab:"어휘",practice:"기능 연습",manage:"관리",system:"시스템",flash:"플래시카드",match:"매치",cross:"크로스워드",reading:"읽기",listening:"듣기",writing:"쓰기",mock:"모의고사",weak:"취약점",community:"커뮤니티",add:"콘텐츠 추가",mine:"내 콘텐츠",account:"계정",profile:"프로필",pricing:"요금",settings:"설정"},
 pt:{home:"Início",vocab:"Vocabulário",practice:"Prática",manage:"Gerenciar",system:"Sistema",flash:"Flashcards",match:"Combinar",cross:"Palavras cruzadas",reading:"Leitura",listening:"Compreensão oral",writing:"Escrita",mock:"Simulado",weak:"Pontos fracos",community:"Comunidade",add:"Adicionar conteúdo",mine:"Meu conteúdo",account:"Conta",profile:"Perfil",pricing:"Preços",settings:"Configurações"},
 de:{home:"Start",vocab:"Wortschatz",practice:"Fertigkeiten",manage:"Verwalten",system:"System",flash:"Karteikarten",match:"Zuordnen",cross:"Kreuzworträtsel",reading:"Lesen",listening:"Hören",writing:"Schreiben",mock:"Probetest",weak:"Schwachstellen",community:"Community",add:"Inhalt hinzufügen",mine:"Meine Inhalte",account:"Konto",profile:"Profil",pricing:"Preise",settings:"Einstellungen"},
 ru:{home:"Главная",vocab:"Словарь",practice:"Навыки",manage:"Управление",system:"Система",flash:"Карточки",match:"Соответствия",cross:"Кроссворд",reading:"Чтение",listening:"Аудирование",writing:"Письмо",mock:"Пробный экзамен",weak:"Слабые места",community:"Сообщество",add:"Добавить материал",mine:"Мои материалы",account:"Аккаунт",profile:"Профиль",pricing:"Тарифы",settings:"Настройки"},
 hi:{home:"होम",vocab:"शब्दावली",practice:"कौशल अभ्यास",manage:"प्रबंधन",system:"सिस्टम",flash:"फ़्लैशकार्ड",match:"मिलान",cross:"क्रॉसवर्ड",reading:"पठन",listening:"श्रवण",writing:"लेखन",mock:"मॉक परीक्षा",weak:"कमज़ोर क्षेत्र",community:"समुदाय",add:"सामग्री जोड़ें",mine:"मेरी सामग्री",account:"खाता",profile:"प्रोफ़ाइल",pricing:"मूल्य",settings:"सेटिंग्स"}
};
export function tr(lang,key){return t[lang]?.[key]||t.en[key]||key}

const EN={
 "ฝึกภาษาอังกฤษในแบบของคุณ":"Practice English your way","Flashcard, Reading, Listening, Writing และแบบทดสอบในที่เดียว":"Flashcards, Reading, Listening, Writing, and mock exams in one place","แผนวันนี้":"Today's plan","นาที":"minutes","ทบทวนคำศัพท์":"Review vocabulary","เริ่มจากทักษะที่คุณเลือกไว้ แล้วกลับมาทบทวนต่อได้ทุกวัน":"Start with your chosen skill and return to review every day","เริ่มแผนวันนี้":"Start today's plan","ความก้าวหน้ารวม":"Total progress","ยังไม่ได้เช็คอินวันนี้":"Not checked in today","ชุด":"sets","เลือกชุดแล้วเริ่มฝึกได้ทันที":"Choose a set and start practicing","เริ่มฝึก":"Start practicing","วนคำจนจำครบ":"Loop words until mastered","จับคู่แข่งกับเวลาและทำลายสถิติ":"Race the clock and beat your record","เติมคำศัพท์ลงตารางไขว้จริง":"Complete a real crossword grid","อ่าน แตะคำ แปล และเก็บศัพท์":"Read, tap, translate, and save words","ฟังบทสนทนาและตอบคำถาม":"Listen to conversations and answer questions","Text Completion และเรียงย่อหน้า":"Text completion and paragraph organization","สร้างและเลือกชุดข้อสอบ":"Create and choose mock exams","ค้นหาชุดจากผู้ใช้อื่น":"Find sets from other learners","เช็คอินรายวัน":"Daily check-in","เช็คอินเพื่อรักษา Streak และรับ XP":"Check in to keep your streak and earn XP","เช็คอิน +20 XP":"Check in +20 XP","เปิด":"Open",
 "บัญชีของฉัน":"My account","เลือกหัวข้อที่ต้องการจัดการ":"Choose what you want to manage","โปรไฟล์":"Profile","ชื่อ รูปภาพ และกิจกรรมการเรียน":"Name, photo, and learning activity","แพ็กเกจและการชำระเงิน":"Plan and billing","ดูสิทธิ์ อัปเกรด หรือจัดการสมาชิก":"View benefits, upgrade, or manage membership","การตั้งค่า":"Settings","ภาษา ธีม และเสียง":"Language, theme, and sound","ข้อมูลและความเป็นส่วนตัว":"Data and privacy","ดาวน์โหลดข้อมูลหรือจัดการบัญชี":"Download data or manage your account","ย้อนกลับ":"Back","บัญชี":"Account",
 "ภาษา":"Language","เลือกภาษาของส่วนติดต่อผู้ใช้":"Choose the interface language","ภาษาที่แสดง":"Display language","สกุลเงินกำหนดอัตโนมัติ: ภาษาไทยใช้ THB และภาษาอื่นใช้ USD":"Currency is selected automatically: Thai uses THB and other languages use USD","ธีม":"Theme","เลือกหน้าตาของ Jumsup":"Choose how Jumsup looks","เลือกโหมดที่สบายตา":"Choose a comfortable appearance","สว่าง":"Light","มืด":"Dark","ตามระบบ":"System","เสียง":"Sound","เปิดหรือปิดเสียงตอบสนอง":"Turn feedback sounds on or off","เสียงเอฟเฟกต์":"Sound effects","เปิด":"On","ปิด":"Off","เปิดเสียงอ่านคำศัพท์และเสียงตอบรับ":"Enable word pronunciation and feedback sounds",
 "เลือกแพ็กเกจที่เหมาะกับคุณ":"Choose the plan that fits you","เริ่มใช้ฟรีได้จริง และอัปเกรดเมื่ออยากฝึกได้มากขึ้น":"Start free and upgrade when you need more practice","เรียนต่อเนื่องในราคาที่เข้าถึงได้":"Keep learning at an accessible price","ราคาจะแสดงเป็น USD ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"Prices are shown in USD for your selected language and match Stripe Checkout","ราคาจะแสดงเป็น THB ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"Prices are shown in THB for your selected language and match Stripe Checkout","เริ่มต้น":"Starter","แพ็กเกจปัจจุบัน":"Current plan","ตลอดไป":"forever","คุ้มที่สุด":"Best value","รายปี":"Yearly","เฉลี่ย":"Equivalent to","เดือน":"month","ประหยัดประมาณ 33%":"save about 33%","ยืดหยุ่น":"Flexible","เหมาะสำหรับลองใช้ Pro ก่อน":"A flexible way to try Pro","ใช้งาน Free อยู่":"Current Free plan","จัดการสมาชิก":"Manage membership","เลือก Pro รายปี":"Choose yearly Pro","เลือก Pro รายเดือน":"Choose monthly Pro","เข้าสู่ระบบเพื่อเลือกแพ็กเกจ":"Sign in to choose a plan","คำถามสำคัญ":"Important questions","ยอดที่ถูกตัดจะตรงกับหน้าเว็บไหม?":"Will the charged amount match the website?","ยกเลิกแล้วข้อมูลหายไหม?":"Will I lose my data after cancelling?","ระบบจะเก็บเงินจริงหรือไม่?":"Will I be charged real money?",
 "เลือกชุดก่อนเข้าสู่หน้าฝึกจริง หรือสร้างชุดของคุณเอง":"Choose a set before starting, or create your own","สร้างชุดใหม่":"Create new set","นำเข้าจาก CSV":"Import CSV","เริ่มฝึก":"Start practice","แก้ไข":"Edit","ลบ":"Delete","ส่วนตัว":"Private","สาธารณะ":"Public","ยังไม่มีชุดฝึกในหมวดนี้":"No practice sets in this category yet","สร้างโดย":"Created by","ข้อ":"questions","ตอบแล้ว":"Answered","ส่งคำตอบ":"Submit answers","เวลาคงเหลือ":"Time remaining","ส่งข้อสอบ":"Submit exam","เปิด Transcript สำหรับโหมดฝึก":"Show transcript for practice mode","ฟังส่วนนี้":"Play this section","ฟังทั้งหมด":"Play all","พัก":"Pause","ต่อ":"Resume","หยุด":"Stop","สำเนียง":"Accent","ความเร็ว":"Speed","คำตอบที่ถูก":"Correct answer","ถูก":"Correct","ผิด":"Incorrect","ไม่ได้ตอบ":"Not answered","ทำอีกครั้ง":"Try again","กลับไปเลือกชุด":"Back to sets","คะแนน":"Score","ทำได้ดี":"Great job","ใกล้ถึงเป้าหมาย":"Almost there","ควรทบทวน":"Needs review",
 "เรียน Flashcards, Match และ Crossword ได้ไม่จำกัด":"Unlimited Flashcards, Match, and Crossword practice","เก็บชุดคำศัพท์ส่วนตัว 3 ชุด":"Keep 3 private vocabulary sets","เก็บชุด Reading, Listening, Writing และ Mock ส่วนตัวอย่างละ 1 ชุด":"Keep 1 private set for each practice skill","แปลคำศัพท์ 10 คำต่อวัน":"Translate 10 words per day","Listening, Writing และ Mock อย่างละ 1 รอบต่อวัน":"1 Listening, Writing, and Mock session per day","ใช้งานและแชร์ชุดใน Community":"Use and share Community sets","เก็บชุดส่วนตัวได้ไม่จำกัด":"Unlimited private sets","แปลคำศัพท์ 100 คำต่อวัน":"Translate 100 words per day","ฝึก Reading, Listening, Writing และ Mock ได้ไม่จำกัด":"Unlimited Reading, Listening, Writing, and Mock practice","นำเข้า CSV ได้สูงสุด 1,000 แถวต่อครั้ง":"Import up to 1,000 CSV rows at a time","สถิติการเรียนและจุดอ่อนแบบละเอียด":"Detailed progress and weak-point insights","ยกเลิกได้ทุกเมื่อ สิทธิ์อยู่ถึงวันสิ้นรอบ":"Cancel anytime; access continues until the billing period ends","สิทธิ์ Pro ครบทุกอย่างเหมือนรายเดือน":"All Pro benefits included","ประหยัดเมื่อเทียบกับการชำระรายเดือน":"Save compared with monthly billing","ฝึกทุกทักษะและ Mock ได้ไม่จำกัด":"Unlimited practice and mock exams","ตรงกัน ระบบส่งทั้งแพ็กเกจและสกุลเงินที่เลือกไป Stripe Checkout หากสกุลเงินนั้นยังไม่พร้อม ระบบจะหยุดและไม่สร้างรายการชำระเงิน":"Yes. The plan and language-based currency are sent together to Stripe Checkout. If unavailable, checkout stops safely.","ไม่หาย ชุดและความคืบหน้ายังอยู่ แต่จะสร้างชุดส่วนตัวเพิ่มหรือเริ่มรอบที่เกินโควตา Free ไม่ได้จนกว่าจะลดจำนวนหรือสมัคร Pro อีกครั้ง":"No. Your sets and progress remain, but Free limits apply until you upgrade again.","ขณะนี้เป็น Stripe Test Mode จึงไม่มีการเรียกเก็บเงินจริง ก่อนเปิดขายต้องยืนยันธุรกิจ เปิด Live Mode และทดสอบรายการเงินจริงมูลค่าต่ำอีกครั้ง":"Stripe is currently in Test Mode, so no real payment is charged.",
 "ฟีเจอร์":"Features","ราคา":"Pricing","เข้าสู่ระบบ":"Sign in","ฝึกอังกฤษครบทั้ง":"Complete English practice for","ศัพท์ ทักษะ และข้อสอบ":"vocabulary, skills, and exams","วางแผนฝึกจากจุดอ่อนของคุณ ทบทวนศัพท์ด้วย Loop และลองข้อสอบคู่ขนานที่สร้างใหม่โดยไม่คัดลอกข้อสอบจริง":"Practice your weak points, review vocabulary with Loop, and try original parallel exams.","เริ่มฝึกฟรี":"Start free","ลองตัวอย่าง":"Try a demo","ไม่ต้องใช้บัตร":"No card required","มีแพ็กเกจฟรี":"Free plan available","ใช้ได้บนมือถือ":"Works on mobile","ยกเลิก":"Cancel","บันทึก":"Save","ตกลง":"OK","ลบถาวร":"Delete permanently","ค้นหา":"Search","ใหม่ล่าสุด":"Newest","ยอดนิยม":"Popular","คะแนนสูงสุด":"Top rated","ยังไม่พบผลลัพธ์":"No results found","ชุดที่พบ":"sets found","เพิ่มเนื้อหา":"Add content","เนื้อหาของฉัน":"My content"
};
const ZH={
 "ฝึกภาษาอังกฤษในแบบของคุณ":"按自己的方式学习英语","Flashcard, Reading, Listening, Writing และแบบทดสอบในที่เดียว":"单词卡、阅读、听力、写作和模拟考试，一站完成","แผนวันนี้":"今日计划","นาที":"分钟","ทบทวนคำศัพท์":"复习词汇","เริ่มจากทักษะที่คุณเลือกไว้ แล้วกลับมาทบทวนต่อได้ทุกวัน":"从你选择的技能开始，每天回来复习","เริ่มแผนวันนี้":"开始今日计划","ความก้าวหน้ารวม":"总进度","ยังไม่ได้เช็คอินวันนี้":"今天尚未签到","ชุด":"套","เลือกชุดแล้วเริ่มฝึกได้ทันที":"选择一套即可开始练习","เริ่มฝึก":"开始练习","วนคำจนจำครบ":"循环复习直到掌握","จับคู่แข่งกับเวลาและทำลายสถิติ":"计时配对并刷新纪录","เติมคำศัพท์ลงตารางไขว้จริง":"完成真正的填字游戏","อ่าน แตะคำ แปล และเก็บศัพท์":"阅读、点击、翻译并收藏单词","ฟังบทสนทนาและตอบคำถาม":"听对话并回答问题","Text Completion และเรียงย่อหน้า":"文本填空与段落排序","สร้างและเลือกชุดข้อสอบ":"创建并选择模拟考试","ค้นหาชุดจากผู้ใช้อื่น":"查找其他学习者的内容","เช็คอินรายวัน":"每日签到","เช็คอินเพื่อรักษา Streak และรับ XP":"签到以保持连续记录并获得 XP","เช็คอิน +20 XP":"签到 +20 XP","เปิด":"打开",
 "บัญชีของฉัน":"我的账户","เลือกหัวข้อที่ต้องการจัดการ":"选择要管理的项目","โปรไฟล์":"个人资料","ชื่อ รูปภาพ และกิจกรรมการเรียน":"姓名、头像和学习活动","แพ็กเกจและการชำระเงิน":"套餐与付款","ดูสิทธิ์ อัปเกรด หรือจัดการสมาชิก":"查看权益、升级或管理会员","การตั้งค่า":"设置","ภาษา ธีม และเสียง":"语言、主题与声音","ข้อมูลและความเป็นส่วนตัว":"数据与隐私","ดาวน์โหลดข้อมูลหรือจัดการบัญชี":"下载数据或管理账户","ย้อนกลับ":"返回","บัญชี":"账户","ภาษา":"语言","เลือกภาษาของส่วนติดต่อผู้ใช้":"选择界面语言","ภาษาที่แสดง":"显示语言","สกุลเงินกำหนดอัตโนมัติ: ภาษาไทยใช้ THB และภาษาอื่นใช้ USD":"货币自动选择：泰语使用 THB，其他语言使用 USD","ธีม":"主题","เลือกหน้าตาของ Jumsup":"选择 Jumsup 的外观","เลือกโหมดที่สบายตา":"选择舒适的显示模式","สว่าง":"浅色","มืด":"深色","ตามระบบ":"跟随系统","เสียง":"声音","เปิดหรือปิดเสียงตอบสนอง":"开启或关闭反馈音效","เสียงเอฟเฟกต์":"音效","เปิด":"开启","ปิด":"关闭","เปิดเสียงอ่านคำศัพท์และเสียงตอบรับ":"启用单词发音和反馈音效",
 "เลือกแพ็กเกจที่เหมาะกับคุณ":"选择适合你的套餐","เริ่มใช้ฟรีได้จริง และอัปเกรดเมื่ออยากฝึกได้มากขึ้น":"免费开始，需要更多练习时再升级","เรียนต่อเนื่องในราคาที่เข้าถึงได้":"以合理价格持续学习","ราคาจะแสดงเป็น USD ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"价格将按所选语言显示为 USD，并与 Stripe 结账页一致","ราคาจะแสดงเป็น THB ตามภาษาที่คุณเลือก และตรงกับ Stripe Checkout":"价格将显示为 THB，并与 Stripe 结账页一致","เริ่มต้น":"入门","แพ็กเกจปัจจุบัน":"当前套餐","ตลอดไป":"永久","คุ้มที่สุด":"最划算","รายปี":"年付","เฉลี่ย":"平均","เดือน":"月","ประหยัดประมาณ 33%":"约省 33%","ยืดหยุ่น":"灵活","เหมาะสำหรับลองใช้ Pro ก่อน":"适合先体验 Pro","ใช้งาน Free อยู่":"正在使用免费版","จัดการสมาชิก":"管理会员","เลือก Pro รายปี":"选择 Pro 年付","เลือก Pro รายเดือน":"选择 Pro 月付","เข้าสู่ระบบเพื่อเลือกแพ็กเกจ":"登录后选择套餐","คำถามสำคัญ":"常见问题","ยอดที่ถูกตัดจะตรงกับหน้าเว็บไหม?":"扣款金额会与网站一致吗？","ยกเลิกแล้วข้อมูลหายไหม?":"取消后数据会丢失吗？","ระบบจะเก็บเงินจริงหรือไม่?":"现在会真实扣款吗？",
 "选择ชุดก่อนเข้าสู่หน้าฝึกจริง หรือสร้างชุดของคุณเอง":"选择内容后开始练习，或创建自己的内容","สร้างชุดใหม่":"新建内容","นำเข้าจาก CSV":"从 CSV 导入","เริ่มฝึก":"开始练习","แก้ไข":"编辑","ลบ":"删除","ส่วนตัว":"私密","สาธารณะ":"公开","ยังไม่มีชุดฝึกในหมวดนี้":"此分类暂无练习内容","สร้างโดย":"创建者","ข้อ":"题","ตอบแล้ว":"已回答","ส่งคำตอบ":"提交答案","เวลาคงเหลือ":"剩余时间","ส่งข้อสอบ":"提交考试","เปิด Transcript สำหรับโหมดฝึก":"显示练习模式文字稿","ฟังส่วนนี้":"播放本段","ฟังทั้งหมด":"全部播放","พัก":"暂停","ต่อ":"继续","หยุด":"停止","สำเนียง":"口音","ความเร็ว":"速度","คำตอบที่ถูก":"正确答案","ถูก":"正确","ผิด":"错误","ไม่ได้ตอบ":"未回答","ทำอีกครั้ง":"再试一次","กลับไปเลือกชุด":"返回内容列表","คะแนน":"分数","ทำได้ดี":"做得很好","ใกล้ถึงเป้าหมาย":"接近目标","ควรทบทวน":"需要复习",
 "เรียน Flashcards, Match และ Crossword ได้ไม่จำกัด":"无限练习单词卡、配对和填字游戏","เก็บชุดคำศัพท์ส่วนตัว 3 ชุด":"保存 3 套私密词汇","เก็บชุด Reading, Listening, Writing และ Mock ส่วนตัวอย่างละ 1 ชุด":"每种技能可保存 1 套私密练习","แปลคำศัพท์ 10 คำต่อวัน":"每天翻译 10 个单词","Listening, Writing และ Mock อย่างละ 1 รอบต่อวัน":"每天各 1 次听力、写作和模拟考试","ใช้งานและแชร์ชุดใน Community":"使用并分享社区内容","เก็บชุดส่วนตัวได้ไม่จำกัด":"无限保存私密内容","แปลคำศัพท์ 100 คำต่อวัน":"每天翻译 100 个单词","ฝึก Reading, Listening, Writing และ Mock ได้ไม่จำกัด":"无限练习阅读、听力、写作和模拟考试","นำเข้า CSV ได้สูงสุด 1,000 แถวต่อครั้ง":"每次最多导入 1,000 行 CSV","สถิติการเรียนและจุดอ่อนแบบละเอียด":"详细学习统计与薄弱点分析","ยกเลิกได้ทุกเมื่อ สิทธิ์อยู่ถึงวันสิ้นรอบ":"可随时取消，权益持续到计费周期结束","สิทธิ์ Pro ครบทุกอย่างเหมือนรายเดือน":"包含全部 Pro 权益","ประหยัดเมื่อเทียบกับการชำระรายเดือน":"比月付更省","ฝึกทุกทักษะและ Mock ได้ไม่จำกัด":"无限技能练习和模拟考试","ฟีเจอร์":"功能","ราคา":"价格","เข้าสู่ระบบ":"登录","เริ่มฝึกฟรี":"免费开始","ลองตัวอย่าง":"试用示例","ยกเลิก":"取消","บันทึก":"保存","ตกลง":"确定","ลบถาวร":"永久删除","ค้นหา":"搜索","ใหม่ล่าสุด":"最新","ยอดนิยม":"热门","คะแนนสูงสุด":"评分最高","ยังไม่พบผลลัพธ์":"未找到结果","ชุดที่พบ":"套内容","เพิ่มเนื้อหา":"添加内容","เนื้อหาของฉัน":"我的内容","เลือกชุดก่อนเข้าสู่หน้าฝึกจริง หรือสร้างชุดของคุณเอง":"选择内容后开始练习，或创建自己的内容"
};

const LOCALIZED={
 ja:{"Practice English your way":"自分らしく英語を練習","Today's plan":"今日のプラン","Review vocabulary":"単語を復習","Start today's plan":"今日のプランを開始","Total progress":"総合進捗","Not checked in today":"今日はまだチェックインしていません","Start practicing":"練習を始める","Daily check-in":"毎日のチェックイン","Open":"開く","My account":"マイアカウント","Choose what you want to manage":"管理する項目を選択","Profile":"プロフィール","Plan and billing":"プランとお支払い","Settings":"設定","Data and privacy":"データとプライバシー","Language":"言語","Choose the interface language":"表示言語を選択","Display language":"表示言語","Currency is selected automatically: Thai uses THB and other languages use USD":"通貨は自動選択されます：タイ語はTHB、その他はUSD","Theme":"テーマ","Light":"ライト","Dark":"ダーク","Sound":"サウンド","Choose the plan that fits you":"あなたに合うプランを選択","Keep learning at an accessible price":"手頃な価格で学習を継続","Starter":"スターター","Current plan":"現在のプラン","Best value":"最もお得","Yearly":"年間","Flexible":"フレキシブル","Manage membership":"メンバーシップ管理","Important questions":"よくある質問","Create new set":"新しいセット","Import CSV":"CSVをインポート","Edit":"編集","Delete":"削除","Private":"非公開","Public":"公開","Submit answers":"回答を提出","Time remaining":"残り時間","Correct":"正解","Incorrect":"不正解","Cancel":"キャンセル","Save":"保存","Search":"検索","Popular":"人気","Newest":"新着"},
 ko:{"Practice English your way":"나만의 방식으로 영어 연습","Today's plan":"오늘의 계획","Review vocabulary":"어휘 복습","Start today's plan":"오늘의 계획 시작","Total progress":"전체 진행률","Not checked in today":"오늘 아직 체크인하지 않음","Start practicing":"연습 시작","Daily check-in":"매일 체크인","Open":"열기","My account":"내 계정","Choose what you want to manage":"관리할 항목을 선택하세요","Profile":"프로필","Plan and billing":"요금제 및 결제","Settings":"설정","Data and privacy":"데이터 및 개인정보","Language":"언어","Choose the interface language":"인터페이스 언어 선택","Display language":"표시 언어","Currency is selected automatically: Thai uses THB and other languages use USD":"통화는 자동 선택됩니다. 태국어는 THB, 그 외 언어는 USD","Theme":"테마","Light":"라이트","Dark":"다크","Sound":"소리","Choose the plan that fits you":"나에게 맞는 요금제 선택","Keep learning at an accessible price":"합리적인 가격으로 계속 학습","Starter":"시작","Current plan":"현재 요금제","Best value":"가장 경제적","Yearly":"연간","Flexible":"유연한 선택","Manage membership":"멤버십 관리","Important questions":"자주 묻는 질문","Create new set":"새 세트 만들기","Import CSV":"CSV 가져오기","Edit":"수정","Delete":"삭제","Private":"비공개","Public":"공개","Submit answers":"답안 제출","Time remaining":"남은 시간","Correct":"정답","Incorrect":"오답","Cancel":"취소","Save":"저장","Search":"검색","Popular":"인기","Newest":"최신"},
 pt:{"Practice English your way":"Pratique inglês do seu jeito","Today's plan":"Plano de hoje","Review vocabulary":"Revisar vocabulário","Start today's plan":"Iniciar plano de hoje","Total progress":"Progresso total","Not checked in today":"Ainda não fez check-in hoje","Start practicing":"Começar a praticar","Daily check-in":"Check-in diário","Open":"Abrir","My account":"Minha conta","Choose what you want to manage":"Escolha o que deseja gerenciar","Profile":"Perfil","Plan and billing":"Plano e cobrança","Settings":"Configurações","Data and privacy":"Dados e privacidade","Language":"Idioma","Choose the interface language":"Escolha o idioma da interface","Display language":"Idioma de exibição","Currency is selected automatically: Thai uses THB and other languages use USD":"A moeda é automática: tailandês usa THB e os demais idiomas usam USD","Theme":"Tema","Light":"Claro","Dark":"Escuro","Sound":"Som","Choose the plan that fits you":"Escolha o plano ideal","Keep learning at an accessible price":"Continue aprendendo por um preço acessível","Starter":"Inicial","Current plan":"Plano atual","Best value":"Melhor custo-benefício","Yearly":"Anual","Flexible":"Flexível","Manage membership":"Gerenciar assinatura","Important questions":"Perguntas importantes","Create new set":"Criar conjunto","Import CSV":"Importar CSV","Edit":"Editar","Delete":"Excluir","Private":"Privado","Public":"Público","Submit answers":"Enviar respostas","Time remaining":"Tempo restante","Correct":"Correto","Incorrect":"Incorreto","Cancel":"Cancelar","Save":"Salvar","Search":"Buscar","Popular":"Popular","Newest":"Mais recentes"},
 de:{"Practice English your way":"Englisch auf deine Art üben","Today's plan":"Heutiger Plan","Review vocabulary":"Wortschatz wiederholen","Start today's plan":"Heutigen Plan starten","Total progress":"Gesamtfortschritt","Not checked in today":"Heute noch nicht eingecheckt","Start practicing":"Übung starten","Daily check-in":"Täglicher Check-in","Open":"Öffnen","My account":"Mein Konto","Choose what you want to manage":"Wähle, was du verwalten möchtest","Profile":"Profil","Plan and billing":"Tarif und Abrechnung","Settings":"Einstellungen","Data and privacy":"Daten und Datenschutz","Language":"Sprache","Choose the interface language":"Sprache der Benutzeroberfläche wählen","Display language":"Anzeigesprache","Currency is selected automatically: Thai uses THB and other languages use USD":"Die Währung wird automatisch gewählt: Thai nutzt THB, alle anderen Sprachen USD","Theme":"Design","Light":"Hell","Dark":"Dunkel","Sound":"Ton","Choose the plan that fits you":"Wähle den passenden Tarif","Keep learning at an accessible price":"Weiterlernen zu einem fairen Preis","Starter":"Einstieg","Current plan":"Aktueller Tarif","Best value":"Bestes Angebot","Yearly":"Jährlich","Flexible":"Flexibel","Manage membership":"Mitgliedschaft verwalten","Important questions":"Wichtige Fragen","Create new set":"Neues Set","Import CSV":"CSV importieren","Edit":"Bearbeiten","Delete":"Löschen","Private":"Privat","Public":"Öffentlich","Submit answers":"Antworten absenden","Time remaining":"Verbleibende Zeit","Correct":"Richtig","Incorrect":"Falsch","Cancel":"Abbrechen","Save":"Speichern","Search":"Suchen","Popular":"Beliebt","Newest":"Neueste"},
 ru:{"Practice English your way":"Практикуйте английский по-своему","Today's plan":"План на сегодня","Review vocabulary":"Повторить слова","Start today's plan":"Начать план на сегодня","Total progress":"Общий прогресс","Not checked in today":"Сегодня отметки ещё нет","Start practicing":"Начать практику","Daily check-in":"Ежедневная отметка","Open":"Открыть","My account":"Мой аккаунт","Choose what you want to manage":"Выберите раздел управления","Profile":"Профиль","Plan and billing":"Тариф и оплата","Settings":"Настройки","Data and privacy":"Данные и конфиденциальность","Language":"Язык","Choose the interface language":"Выберите язык интерфейса","Display language":"Язык интерфейса","Currency is selected automatically: Thai uses THB and other languages use USD":"Валюта выбирается автоматически: для тайского THB, для остальных языков USD","Theme":"Тема","Light":"Светлая","Dark":"Тёмная","Sound":"Звук","Choose the plan that fits you":"Выберите подходящий тариф","Keep learning at an accessible price":"Продолжайте учиться по доступной цене","Starter":"Начальный","Current plan":"Текущий тариф","Best value":"Выгоднее всего","Yearly":"Годовой","Flexible":"Гибкий","Manage membership":"Управление подпиской","Important questions":"Важные вопросы","Create new set":"Создать набор","Import CSV":"Импорт CSV","Edit":"Изменить","Delete":"Удалить","Private":"Личное","Public":"Общедоступное","Submit answers":"Отправить ответы","Time remaining":"Осталось времени","Correct":"Верно","Incorrect":"Неверно","Cancel":"Отмена","Save":"Сохранить","Search":"Поиск","Popular":"Популярное","Newest":"Новое"},
 hi:{"Practice English your way":"अपने तरीके से अंग्रेज़ी का अभ्यास करें","Today's plan":"आज की योजना","Review vocabulary":"शब्दावली दोहराएँ","Start today's plan":"आज की योजना शुरू करें","Total progress":"कुल प्रगति","Not checked in today":"आज चेक-इन नहीं किया","Start practicing":"अभ्यास शुरू करें","Daily check-in":"दैनिक चेक-इन","Open":"खोलें","My account":"मेरा खाता","Choose what you want to manage":"जिसे प्रबंधित करना है उसे चुनें","Profile":"प्रोफ़ाइल","Plan and billing":"प्लान और बिलिंग","Settings":"सेटिंग्स","Data and privacy":"डेटा और गोपनीयता","Language":"भाषा","Choose the interface language":"इंटरफ़ेस भाषा चुनें","Display language":"प्रदर्शन भाषा","Currency is selected automatically: Thai uses THB and other languages use USD":"मुद्रा अपने आप चुनी जाती है: थाई के लिए THB और अन्य भाषाओं के लिए USD","Theme":"थीम","Light":"हल्का","Dark":"गहरा","Sound":"ध्वनि","Choose the plan that fits you":"अपने लिए सही प्लान चुनें","Keep learning at an accessible price":"किफ़ायती मूल्य पर सीखते रहें","Starter":"शुरुआती","Current plan":"वर्तमान प्लान","Best value":"सबसे किफ़ायती","Yearly":"वार्षिक","Flexible":"लचीला","Manage membership":"सदस्यता प्रबंधित करें","Important questions":"महत्वपूर्ण प्रश्न","Create new set":"नया सेट बनाएँ","Import CSV":"CSV आयात करें","Edit":"संपादित करें","Delete":"हटाएँ","Private":"निजी","Public":"सार्वजनिक","Submit answers":"उत्तर जमा करें","Time remaining":"शेष समय","Correct":"सही","Incorrect":"गलत","Cancel":"रद्द करें","Save":"सहेजें","Search":"खोजें","Popular":"लोकप्रिय","Newest":"नवीनतम"}
};

Object.assign(EN,{
 "แตะเพื่อดูคำแปล":"Tap to reveal the translation","สำคัญ · มีนัยสำคัญ":"important · significant","ยังไม่จำ":"Still learning","จำได้":"Know it","ทักษะหลัก":"core skills","ข้อใน Full Mock":"questions in a Full Mock","นาทีต่อวัน":"minutes a day","ฟรี":"Free","เริ่มเรียนได้ทันที":"Start learning now","ฝึกให้ตรงจุด":"Focused practice","หนึ่งที่สำหรับการเตรียมอังกฤษ A-Level":"One place for A-Level English preparation","ไม่ต้องเปิดหลายแอป และไม่ต้องสร้างชุดเองก่อนเริ่มเรียน":"No need to switch between apps or create a set before you start.","จำศัพท์ด้วย Loop":"Memorize vocabulary with Loop","คำที่ยังไม่จำจะวนกลับมา และบันทึกไว้ทบทวนได้เสมอ":"Words you are still learning return automatically and remain available for review.","Reading พร้อมเครื่องมือ":"Reading with built-in tools","ไฮไลต์ แตะคำ แปล และเก็บคำที่ไม่รู้เข้า Flashcard":"Highlight, tap, translate, and save unfamiliar words to Flashcards.","Listening ตามรูปแบบข้อสอบ":"Exam-style Listening","ฟังบทสนทนา ซ่อน Transcript และตอบคำถามตามบริบท":"Listen to conversations, hide the transcript, and answer in context.","Mock Exam คู่ขนาน":"Original parallel Mock Exams","ซ้อมเวลา ตรวจคะแนน และดูคำอธิบายหลังส่งคำตอบ":"Practice under time limits, check scores, and review explanations after submitting.","เริ่มง่าย":"Easy to start","รู้ว่าต้องทำอะไรต่อในทุกวัน":"Know what to do next every day","เลือกเป้าหมาย":"Choose a goal","กำหนดทักษะและเวลาที่ต้องการฝึก":"Choose the skills and time you want to practice.","ฝึกตามแผน":"Follow your plan","เริ่มจากชุดพร้อมเรียนและจุดอ่อนของคุณ":"Start with ready-to-learn sets and your weak points.","วัดพัฒนาการ":"Track progress","ดูคะแนน คำที่จำได้ และกลับมาทบทวน":"See scores, mastered words, and return to review.","เริ่มต้นโดยไม่ต้องจ่าย":"Start without paying","Free ใช้งานได้จริง":"A genuinely useful Free plan","Pro เมื่ออยากฝึกได้มากขึ้น":"Pro when you want more practice","ดูแพ็กเกจทั้งหมด":"See all plans","ฝึกอังกฤษให้เป็นระบบในแบบของคุณ":"Build a consistent English practice routine your way","ต่อเดือน":"per month","หรือรายปีเฉลี่ย":"or yearly, equivalent to"
});
Object.assign(ZH,{
 "ฝึกอังกฤษครบทั้ง":"完整练习英语","ศัพท์ ทักษะ และข้อสอบ":"词汇、技能与考试","วางแผนฝึกจากจุดอ่อนของคุณ ทบทวนศัพท์ด้วย Loop และลองข้อสอบคู่ขนานที่สร้างใหม่โดยไม่คัดลอกข้อสอบจริง":"针对薄弱点制定练习计划，用 Loop 复习词汇，并尝试原创的平行模拟题。","ไม่ต้องใช้บัตร":"无需银行卡","มีแพ็กเกจฟรี":"提供免费方案","ใช้ได้บนมือถือ":"支持手机使用","แตะเพื่อดูคำแปล":"点击查看翻译","ยังไม่จำ":"还在学习","จำได้":"已掌握","ทักษะหลัก":"核心技能","ข้อใน Full Mock":"完整模拟题数量","นาทีต่อวัน":"每天分钟","ฟรี":"免费","เริ่มเรียนได้ทันที":"立即开始学习","ฝึกให้ตรงจุด":"针对性练习","หนึ่งที่สำหรับการเตรียมอังกฤษ A-Level":"一站式准备 A-Level 英语","ไม่ต้องเปิดหลายแอป และไม่ต้องสร้างชุดเองก่อนเริ่มเรียน":"无需切换多个应用，也无需先创建内容。","จำศัพท์ด้วย Loop":"用 Loop 记忆词汇","คำที่ยังไม่จำจะวนกลับมา และบันทึกไว้ทบทวนได้เสมอ":"尚未掌握的单词会自动回来，并可随时复习。","Reading พร้อมเครื่องมือ":"带工具的阅读练习","ไฮไลต์ แตะคำ แปล และเก็บคำที่ไม่รู้เข้า Flashcard":"高亮、点击、翻译，并把生词保存到单词卡。","Listening ตามรูปแบบข้อสอบ":"考试形式的听力练习","ฟังบทสนทนา ซ่อน Transcript และตอบคำถามตามบริบท":"听对话、隐藏文字稿，并根据语境回答。","Mock Exam คู่ขนาน":"原创平行模拟考试","ซ้อมเวลา ตรวจคะแนน และดูคำอธิบายหลังส่งคำตอบ":"限时练习、查看分数，并在提交后阅读解析。","เริ่มง่าย":"轻松开始","รู้ว่าต้องทำอะไรต่อในทุกวัน":"每天都知道下一步该做什么","เลือกเป้าหมาย":"选择目标","กำหนดทักษะและเวลาที่ต้องการฝึก":"选择想练习的技能和时间。","ฝึกตามแผน":"按计划练习","เริ่มจากชุดพร้อมเรียนและจุดอ่อนของคุณ":"从现成内容和你的薄弱点开始。","วัดพัฒนาการ":"跟踪进步","ดูคะแนน คำที่จำได้ และกลับมาทบทวน":"查看分数和已掌握单词，并随时复习。","เริ่มต้นโดยไม่ต้องจ่าย":"免费开始","Free ใช้งานได้จริง":"真正实用的免费方案","Pro เมื่ออยากฝึกได้มากขึ้น":"需要更多练习时升级 Pro","ดูแพ็กเกจทั้งหมด":"查看全部套餐","ฝึกอังกฤษให้เป็นระบบในแบบของคุณ":"以自己的方式建立系统的英语练习","ต่อเดือน":"每月","หรือรายปีเฉลี่ย":"或年付平均"
});

export function localizePage(root,lang){
 if(lang==="th")return;
 const primary=lang==="zh"?ZH:EN,secondary=LOCALIZED[lang]||{};
 const translate=value=>{const leading=value.match(/^\s*/)?.[0]||"",trailing=value.match(/\s*$/)?.[0]||"",key=value.trim();if(!key)return value;let first=primary[key];if(!first&&key.startsWith("✓ "))first=`✓ ${primary[key.slice(2)]||key.slice(2)}`;if(!first&&key.startsWith("Pro เริ่ม "))first=key.replace("Pro เริ่ม ",lang==="zh"?"Pro 起价 ":"Pro starts at ").replaceAll("/เดือน",lang==="zh"?"/月":"/month").replace(" หรือรายปีเฉลี่ย ",lang==="zh"?"，或年付平均 ":", or yearly equivalent to ");first=first||key;return leading+(secondary[first]||first)+trailing};
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
 while((node=walker.nextNode())){if(node.parentElement?.closest("script,style"))continue;node.nodeValue=translate(node.nodeValue)}
 root.querySelectorAll("[placeholder],[aria-label],[title]").forEach(el=>{for(const attr of ["placeholder","aria-label","title"]){const value=el.getAttribute(attr);if(value)el.setAttribute(attr,translate(value))}});
}
