import { escapeHtml } from "../../lib/utils.js";
const money=(amount,currency)=>new Intl.NumberFormat(currency==="thb"?"th-TH":"en-US",{style:"currency",currency:String(currency||"thb").toUpperCase()}).format((amount||0)/100);
export function renderAdmin(data={}){
 const o=data.overview||{},googlePct=Math.min(100,Math.round((o.google_characters||0)/(o.google_cap||400000)*100)),revenue=Object.entries(o.revenue||{}).map(([c,v])=>money(v,c)).join(" · ")||"—";
 const warning=!o.google_configured||googlePct>=90?"danger":googlePct>=70?"warning":"ok",freeRisk=(o.free_users||0)>=500&&(!o.paid||o.paid/o.users<.02);
 return `<div class="admin-center"><div class="admin-toolbar"><div><span class="tag pink">ADMIN ONLY</span><h2>Admin Center</h2><p>ตรวจงานค้าง รายได้ สิทธิ์แจกฟรี และต้นทุนระบบจากหน้าเดียว</p></div><button class="btn" data-action="admin-refresh">รีเฟรชข้อมูล</button></div>
 <div class="admin-metrics"><div><small>ผู้ใช้ทั้งหมด</small><strong>${o.users??"—"}</strong></div><div><small>สมาชิก Stripe Live</small><strong>${o.paid??"—"}</strong></div><div><small>รายได้เดือนนี้</small><strong>${escapeHtml(revenue)}</strong></div><div><small>คำแปลวันนี้</small><strong>${o.translations_today??"—"}</strong></div></div>
 <div class="admin-alert ${warning}"><b>Google Translation ${o.google_configured?googlePct+"%":"ยังไม่ได้ตั้ง API Key"}</b><span>${Number(o.google_characters||0).toLocaleString()} / ${Number(o.google_cap||400000).toLocaleString()} ตัวอักษรเดือนนี้</span><div><i style="width:${googlePct}%"></i></div>${!o.google_configured?`<small>ระบบจะใช้พจนานุกรม Offline/Community เท่านั้นจนกว่าจะตั้งค่า Key</small>`:googlePct>=70?`<small>ใกล้เพดานแล้ว ระบบหยุดเรียก Google อัตโนมัติเมื่อถึง 400,000 ตัวอักษร</small>`:""}</div>
 ${freeRisk?`<div class="admin-cost-warning"><b>เตือนสัดส่วนผู้ใช้ฟรี</b><span>มีผู้ใช้ฟรี ${Number(o.free_users).toLocaleString()} คน แต่สมาชิกจ่ายเงินต่ำกว่า 2% ควรตรวจต้นทุนก่อนแจกสิทธิ์เพิ่ม</span></div>`:""}
 <div class="admin-queue-tabs"><span>งานค้าง</span><b>คำแปล ${o.pending_dictionary??0}</b><b>รายงาน ${o.pending_reports??0}</b><b>คืนเงิน ${o.pending_refunds??0}</b><b>Gift Code ${o.active_codes??0}</b></div>
 <section class="admin-section"><div class="admin-section-head"><div><h3>พจนานุกรมชุมชน</h3><p>ตรวจทุกคำก่อนเผยแพร่ให้ผู้ใช้ทั้งหมด</p></div></div><div class="admin-list">${(data.dictionary||[]).map(x=>`<article><div><b>${escapeHtml(x.source_word)}</b><small>${escapeHtml(x.target_language)} · ${new Date(x.created_at).toLocaleDateString()}</small><input data-dictionary-meaning="${x.id}" value="${escapeHtml(x.suggested_meaning)}" maxlength="300"></div><div class="actions"><button class="btn btn-primary" data-action="admin-dictionary-approve" data-id="${x.id}">อนุมัติ</button><button class="btn btn-danger" data-action="admin-dictionary-reject" data-id="${x.id}">ปฏิเสธ</button></div></article>`).join("")||"<p class='tool-note'>ไม่มีคำแปลรอตรวจ</p>"}</div></section>
 <section class="admin-section"><div class="admin-section-head"><div><h3>รายงาน Community</h3><p>ตรวจเนื้อหาที่ถูกรายงานก่อนดำเนินการเพิ่มเติม</p></div></div><div class="admin-list">${(data.reports||[]).map(x=>`<article><div><b>${escapeHtml(x.content_type)} · ${escapeHtml(x.content_id)}</b><small>${escapeHtml(x.reason)} · ${new Date(x.created_at).toLocaleDateString()}</small></div><div class="actions"><button class="btn btn-primary" data-action="admin-report-resolve" data-id="${x.id}">ดำเนินการแล้ว</button><button class="btn" data-action="admin-report-dismiss" data-id="${x.id}">ยกเลิกการรายงาน</button></div></article>`).join("")||"<p class='tool-note'>ไม่มีรายงานรอตรวจ</p>"}</div></section>
 <section class="admin-section"><div class="admin-section-head"><div><h3>แจก Gift Code</h3><p>จำกัด 1–90 วัน, 1–100 ครั้ง, อายุไม่เกิน 90 วัน และภาระรวมไม่เกิน 5,000 Pro-days</p></div></div><div class="admin-gift-form"><input id="adminGiftCode" placeholder="เช่น LAUNCH2026" maxlength="32"><label>วัน Pro<input id="adminGiftDays" type="number" value="7" min="1" max="90"></label><label>จำนวนสิทธิ์<input id="adminGiftUses" type="number" value="10" min="1" max="100"></label><label>หมดอายุใน<input id="adminGiftExpiry" type="number" value="30" min="1" max="90"></label><button class="btn btn-primary" data-action="admin-create-gift">สร้างโค้ด</button></div><div class="admin-list">${(data.gifts||[]).map(x=>`<article><div><b>${escapeHtml(x.code)}</b><small>${x.pro_days} วัน · ใช้ ${x.used_count}/${x.max_uses} · ${x.active?"ใช้งานอยู่":"ปิดแล้ว"}${x.expires_at?` · หมดอายุ ${new Date(x.expires_at).toLocaleDateString()}`:""}</small></div>${x.active?`<button class="btn btn-danger" data-action="admin-gift-revoke" data-id="${x.id}">ปิดโค้ด</button>`:""}</article>`).join("")||"<p class='tool-note'>ยังไม่มี Gift Code</p>"}</div></section>
 <section class="admin-section"><div class="admin-section-head"><div><h3>คำขอคืนเงิน</h3><p>การคืนเงินจริงต้องกดยืนยันจากรายการและทุกคำสั่งถูกบันทึก Audit Log</p></div><button class="btn" data-action="admin-load-refunds">โหลดคิวคืนเงิน</button></div><div id="adminRefundQueue"></div></section></div>`;
}
