import { Header } from "../../components/ui.js";
import { languages } from "../../lib/i18n.js";
import { escapeHtml } from "../../lib/utils.js";

export function renderSettings(s){
 const username=s.profile?.username||"";
 return `${Header("SYSTEM","Settings","จัดการบัญชี ความเป็นส่วนตัว และประสบการณ์การเรียน","Settings")}<div class="settings-shell">
 ${s.user?`<section class="settings-card account-settings-card"><div class="settings-card-head"><div class="settings-head-icon account-icon">☺</div><div><h2>บัญชีและโปรไฟล์</h2><p>ชื่อผู้ใช้คือชื่อเดียวที่คนอื่นเห็นใน Community</p></div></div><div class="account-setting-form"><label><span>ชื่อผู้ใช้</span><small>3–24 ตัวอักษร ใช้ตัวอักษร ตัวเลข หรือ _</small><div class="account-setting-input"><input id="settingsUsername" maxlength="24" value="${escapeHtml(username)}" autocomplete="off"><button class="btn btn-primary" data-action="save-username" data-input="settingsUsername">บันทึก</button></div></label><div class="private-account-note"><b>อีเมลถูกเก็บเป็นส่วนตัว</b><small>ใช้สำหรับเข้าสู่ระบบและความปลอดภัยเท่านั้น ไม่แสดงบนโปรไฟล์สาธารณะ</small></div></div></section>`:""}
 <section class="settings-card"><div class="settings-card-head"><div class="settings-head-icon language-icon">文</div><div><h2>ภาษา</h2><p>เลือกภาษาของส่วนติดต่อผู้ใช้</p></div></div><div class="language-picker">${languages.map(([id,name])=>`<button class="language-option ${s.lang===id?"selected":""}" data-lang="${id}"><span class="language-native">${name}</span><span class="language-check">${s.lang===id?"✓":""}</span></button>`).join("")}</div></section>
 <section class="settings-card"><div class="settings-card-head"><div class="settings-head-icon theme-icon">◐</div><div><h2>ธีม</h2><p>เลือกโหมดที่สบายตา</p></div></div><div class="theme-choice-grid"><button class="theme-choice ${s.theme==="light"?"selected":""}" data-theme-choice="light"><span class="theme-preview light-preview"><i></i><i></i><i></i></span><span><b>สว่าง</b><small>Warm light appearance</small></span></button><button class="theme-choice ${s.theme==="dark"?"selected":""}" data-theme-choice="dark"><span class="theme-preview dark-preview"><i></i><i></i><i></i></span><span><b>มืด</b><small>Soft charcoal appearance</small></span></button></div></section>
 <section class="settings-card"><div class="settings-card-head"><div class="settings-head-icon sound-icon">🔊</div><div><h2>เสียง</h2><p>เปิดหรือปิดเสียงตอบสนอง</p></div></div><div class="setting-row-clean"><div><b>เสียงเอฟเฟกต์</b><small>${s.sound?"เปิด":"ปิด"}</small></div><label class="switch"><input id="soundToggle" type="checkbox" ${s.sound?"checked":""}><span></span></label></div></section>
 ${s.user?`<section class="settings-card compact-account-links"><div class="settings-card-head"><div class="settings-head-icon security-icon">✓</div><div><h2>ความปลอดภัยและสมาชิก</h2><p>จัดการการสมัครสมาชิกหรือข้อมูลบัญชีเมื่อต้องการ</p></div></div><div class="settings-link-row"><button class="btn" data-nav="profile">ไปที่โปรไฟล์</button><button class="btn" data-action="open-membership-settings">การสมัครสมาชิก</button></div></section>`:""}
 </div>`;
}
