import { Header } from "../../components/ui.js";
import { escapeHtml } from "../../lib/utils.js";

export function renderCommunity(s,query="",tab="vocab"){
 const q=query.toLowerCase(),sort=s.communitySort||"popular";
 let items=(s.community||[]).filter(x=>x.type===tab&&(!q||x.title.toLowerCase().includes(q)||x.creator.toLowerCase().includes(q)));
 const score=x=>(x.importCount||0)*3+(x.likeCount||0)*2+(x.ratingCount||0)*(x.rating||0);
 items=[...items].sort((a,b)=>sort==="new"?String(b.createdAt||"").localeCompare(String(a.createdAt||"")):sort==="rating"?(b.rating||0)-(a.rating||0):score(b)-score(a));
 return `${Header("COMMUNITY","Community Search","ค้นหา เปรียบเทียบ และนำเข้าชุดฝึกจากผู้สร้างคนอื่น","Online Library")}
 <div class="community-summary"><div><strong>${items.length}</strong><small>ชุดที่พบ</small></div><div><strong>${items.reduce((n,x)=>n+(x.importCount||0),0)}</strong><small>การนำเข้า</small></div><div><strong>${items.length?(items.reduce((n,x)=>n+(x.rating||0),0)/items.length).toFixed(1):"-"}</strong><small>คะแนนเฉลี่ย</small></div></div>
 <div class="tabs"><button class="tab ${tab==="vocab"?"active":""}" data-community-tab="vocab">ชุดคำศัพท์</button><button class="tab ${tab==="skill"?"active":""}" data-community-tab="skill">ชุดฝึกทักษะ</button></div>
 <div class="toolbar-row"><input id="communitySearch" class="search-input" value="${escapeHtml(query)}" placeholder="ค้นหาชื่อชุด หรือ username ผู้สร้าง..."><select id="communitySort" class="community-sort"><option value="popular" ${sort==="popular"?"selected":""}>ยอดนิยม</option><option value="rating" ${sort==="rating"?"selected":""}>คะแนนสูงสุด</option><option value="new" ${sort==="new"?"selected":""}>ใหม่ล่าสุด</option></select><button class="btn" data-action="community-search">ค้นหา</button><button class="btn" data-action="community-refresh">รีเฟรช</button></div>
 ${!s.user?`<div class="card soft community-guest"><p>คุณดูชุดและสถิติได้โดยไม่ต้อง Login แต่ต้องเข้าสู่ระบบก่อนนำเข้าหรือให้คะแนนบนระบบออนไลน์</p><button class="btn btn-primary" data-action="login-google">เข้าสู่ระบบ Google</button></div>`:""}
 <div class="grid g2 community-grid">${items.map(x=>`<article class="card community-card"><div class="card-head"><span class="tag ${x.official?"blue":"green"}">${x.official?"OFFICIAL":"COMMUNITY"}</span><span class="community-kind">${escapeHtml(x.kind||x.type)}</span></div><h3>${escapeHtml(x.title)}</h3><p>${x.count||1} รายการ · สร้างโดย <b>@${escapeHtml(x.creator)}</b></p><div class="community-metrics"><span title="คะแนน">★ <b>${Number(x.rating||0).toFixed(1)}</b> <small>(${x.ratingCount||0})</small></span><span title="ถูกใจ">♥ <b>${x.likeCount||0}</b></span><span title="นำเข้า">⇩ <b>${x.importCount||0}</b></span></div><div class="actions"><button class="btn btn-primary" data-action="import-community" data-id="${x.id}" data-type="${x.type}">นำเข้า</button><button class="btn ${x.liked?"btn-liked":""}" data-action="like-community" data-id="${x.id}">${x.liked?"♥ ถูกใจแล้ว":"♡ ถูกใจ"}</button><button class="btn" data-action="review-community" data-id="${x.id}">ให้คะแนน</button><button class="btn" data-action="report-community" data-id="${x.id}">รายงาน</button></div></article>`).join("")||"<div class='empty'>ยังไม่พบผลลัพธ์</div>"}</div>`;
}
